# Generated by Django 6.0.2 on 2026-02-21 06:07

import apps.profiles.models.upload_paths
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('zipcode', models.CharField(blank=True, default='', max_length=9, verbose_name='CEP')),
                ('street', models.CharField(max_length=255, verbose_name='endereco')),
                ('number', models.CharField(max_length=20, verbose_name='numero')),
                ('complement', models.CharField(blank=True, default='', max_length=255, verbose_name='complemento')),
                ('neighborhood', models.CharField(max_length=120, verbose_name='bairro')),
                ('city', models.CharField(max_length=120, verbose_name='cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goias'), ('MA', 'Maranhao'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Para'), ('PB', 'Paraiba'), ('PR', 'Parana'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondonia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'Sao Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='estado')),
                ('country', models.CharField(default='Brasil', max_length=80, verbose_name='pais')),
            ],
            options={
                'verbose_name': 'endereco',
                'verbose_name_plural': 'enderecos',
                'ordering': ['state', 'city', 'street', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('widowed', 'Viuvo(a)'), ('stable_union', 'Uniao estavel'), ('not_informed', 'Nao informado')], default='', max_length=20, verbose_name='estado civil')),
                ('education_level', models.CharField(blank=True, choices=[('incomplete_elementary', 'Fundamental incompleto'), ('complete_elementary', 'Fundamental completo'), ('incomplete_high_school', 'Medio incompleto'), ('complete_high_school', 'Medio completo'), ('incomplete_college', 'Superior incompleto'), ('complete_college', 'Superior completo'), ('postgraduate', 'Pos-graduacao'), ('master', 'Mestrado'), ('doctorate', 'Doutorado'), ('not_informed', 'Nao informado')], default='', max_length=30, verbose_name='nivel de escolaridade')),
                ('mother_name', models.CharField(blank=True, default='', max_length=255, verbose_name='nome da mae')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Feminino'), ('male', 'Masculino'), ('non_binary', 'Nao binario'), ('other', 'Outro'), ('not_informed', 'Nao informado')], default='', max_length=20, verbose_name='sexo')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='profiles.address', verbose_name='endereco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.CharField(help_text='Formato: (00) 00000-0000', max_length=20, verbose_name='numero')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='profiles.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'telefone',
                'verbose_name_plural': 'telefones',
            },
        ),
        migrations.CreateModel(
            name='CPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, verbose_name='numero do CPF')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpf', to='profiles.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'cpf',
                'verbose_name_plural': 'cpfs',
            },
        ),
        migrations.CreateModel(
            name='AddressProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file', models.FileField(help_text='Aceita imagem ou PDF.', upload_to=apps.profiles.models.upload_paths.address_proof_upload_path, verbose_name='arquivo')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='descricao')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_proofs', to='profiles.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'comprovante de endereco',
                'verbose_name_plural': 'comprovantes de endereco',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file', models.FileField(help_text='Preferencialmente PDF.', upload_to=apps.profiles.models.upload_paths.school_certificate_upload_path, verbose_name='arquivo')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_certificate', to='profiles.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'certificado escolar',
                'verbose_name_plural': 'certificados escolares',
            },
        ),
        migrations.CreateModel(
            name='SchoolTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file', models.FileField(help_text='Preferencialmente PDF.', upload_to=apps.profiles.models.upload_paths.school_transcript_upload_path, verbose_name='arquivo')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_transcript', to='profiles.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'historico escolar',
                'verbose_name_plural': 'historicos escolares',
            },
        ),
        migrations.CreateModel(
            name='PersonalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('document_type', models.CharField(choices=[('cnh', 'CNH'), ('rg', 'RG')], max_length=10, verbose_name='tipo de documento')),
                ('number', models.CharField(blank=True, default='', max_length=40, verbose_name='numero')),
                ('file', models.FileField(help_text='Arquivo do documento (imagem ou PDF).', upload_to=apps.profiles.models.upload_paths.personal_document_upload_path, verbose_name='arquivo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_documents', to='profiles.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'documento pessoal',
                'verbose_name_plural': 'documentos pessoais',
                'ordering': ['document_type', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'document_type'), name='unique_personal_document_per_type')],
            },
        ),
    ]
