# Generated by Django 6.0.2 on 2026-03-24 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiImageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_text', models.TextField(blank=True, help_text='Texto do prompt enviado ao Gemini', null=True)),
                ('image_path', models.CharField(blank=True, help_text='Caminho local da imagem gerada/alterada', max_length=500, null=True)),
                ('request_data', models.JSONField(blank=True, help_text='Dados enviados na requisição', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Dados de resposta da API Gemini', null=True)),
                ('response_text', models.TextField(blank=True, help_text='Texto da resposta Gemini', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log Gemini Image',
                'verbose_name_plural': 'Logs Gemini Image',
                'ordering': ['-created_at'],
            },
        ),
    ]
