# Generated by Django 6.0.3 on 2026-04-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_alter_visitor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='christianity_type',
            field=models.CharField(blank=True, choices=[('evangelical_protestant', 'Evangélica/Protestante'), ('roman_catholic', 'Católico Romano'), ('orthodox_catholic', 'Católico Ortodoxo'), ('other', 'Outro')], default='', max_length=40, verbose_name='ramo do cristianismo'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='religion',
            field=models.CharField(blank=True, choices=[('christianity', 'Cristianismo'), ('spiritism', 'Espiritismo'), ('umbanda_candomble', 'Umbanda/Candomblé'), ('islam', 'Islamismo'), ('judaism', 'Judaísmo'), ('buddhism', 'Budismo'), ('no_religion', 'Sem religião'), ('other', 'Outra')], default='', max_length=40, verbose_name='religião'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cadastro online realizado'), (2, 'Dados iniciais salvos - online'), (3, 'Endereço salvo - online'), (4, 'Dados religiosos salvos - online'), (5, 'Aguardando visita presencial'), (11, 'Visitante presencial registrado'), (12, 'Dados iniciais salvos - presencial'), (13, 'Endereço salvo - presencial'), (14, 'Dados religiosos salvos - presencial'), (15, 'Aguardando coleta do presente de boas-vindas'), (21, 'Aguardando contato da equipe de recepção')], default=1, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='EvangelicalChurchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('church_name', models.CharField(blank=True, default='', max_length=255, verbose_name='igreja')),
                ('is_in_communion', models.BooleanField(blank=True, null=True, verbose_name='está em comunhão')),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evangelical_church_info', to='visitors.visitor', verbose_name='visitante')),
            ],
            options={
                'verbose_name': 'informação de igreja evangélica',
                'verbose_name_plural': 'informações de igreja evangélica',
            },
        ),
    ]
