# Generated by Django 5.1.15 on 2026-07-29 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('channels', '0002_whatsappnumber_fallback_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('secret', models.CharField(blank=True, default='', max_length=200)),
                ('events', models.CharField(default='status,inbound', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('last_status', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='accounts.account')),
            ],
            options={
                'verbose_name': 'webhook do app',
                'verbose_name_plural': 'webhooks dos apps',
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(help_text='Shell HTML com {{title}}, {{content}} e {{service_name}}.')),
                ('brand_name', models.CharField(blank=True, default='', max_length=80)),
                ('accent_color', models.CharField(blank=True, default='#172033', max_length=9)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_template', to='accounts.account')),
            ],
            options={
                'verbose_name': 'template de e-mail',
                'verbose_name_plural': 'templates de e-mail',
            },
        ),
    ]
