# Generated by Django 5.1.15 on 2026-08-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ai_adapt',
            field=models.BooleanField(default=True, help_text='Adaptar conteúdo por canal com IA no pipeline (fail-open).'),
        ),
    ]
