"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import socket
from datetime import timedelta
from pathlib import Path

import environ

from core.environment import resolve_environment, resolve_external_fakes

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# django-environ: toda config sensível vem do backend/.env (ponto único de config).
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# ── APP_ENV / TEST_MODE ───────────────────────────────────────────────────
# Modo de teste integrado: simula CPFHub (aceita qualquer CPF bem formado), força WhatsApp
# check_numbers=True, usa código OTP fixo e aponta Asaas pro sandbox. Ligado pelo .env
# (`TEST_MODE=1`). TRAVA anti-prod única e correta: `socket.gethostname() ∈
# TEST_MODE_ALLOWED_HOSTS` (lista explícita, default vazia). **Não** trava por nome de
# settings module — o `core.prod_settings` é usado tanto em prod real quanto em STAGING
# ISOLADO (test-v7m), que não é prod: tem DB local + Asaas sandbox + DEBUG=true. O que
# protege prod é o HOSTNAME, não o módulo (o .env do prod real fica num host NÃO listado).
# Falha → ImproperlyConfigured no import. Source of truth único: este settings.
TEST_MODE_ALLOWED_HOSTS = env.list("TEST_MODE_ALLOWED_HOSTS", default=[])
_legacy_test_mode = env.bool("TEST_MODE", default=False)

_environment = resolve_environment(
    app_env=env("APP_ENV", default="test" if _legacy_test_mode else "prod"),
    legacy_test_mode=_legacy_test_mode,
    hostname=socket.gethostname(),
    allowed_test_hosts=TEST_MODE_ALLOWED_HOSTS,
)
APP_ENV = _environment.app_env
TEST_MODE = _environment.test_mode
TEST_MODE_OTP_CODE = env("TEST_MODE_OTP_CODE", default="000000")
TEST_DATA_TTL_HOURS = env.int("TEST_DATA_TTL_HOURS", default=24)
TEST_COLLABORATOR_PHONE = env("TEST_COLLABORATOR_PHONE", default="5511999990001")
TEST_COLLABORATOR_CPF = env("TEST_COLLABORATOR_CPF", default="52998224725")
TEST_COLLABORATOR_EMAIL = env(
    "TEST_COLLABORATOR_EMAIL", default="e2e-promotor@v7m.test"
)
TEST_EXTERNAL_ADAPTERS = resolve_external_fakes(
    app_env=APP_ENV,
    requested=env.bool("TEST_EXTERNAL_ADAPTERS", default=False),
)
TEST_KYC_OUTCOME = env("TEST_KYC_OUTCOME", default="approved").strip().lower()
if TEST_KYC_OUTCOME not in {"approved", "rejected", "review"}:
    raise ValueError("TEST_KYC_OUTCOME deve ser approved, rejected ou review.")
TEST_MODE_ASAAS_SANDBOX_URL = env(
    "TEST_MODE_ASAAS_SANDBOX_URL", default="https://api-sandbox.asaas.com"
)
# CORS (django-cors-headers) — config no .env (CONVENTION §10: um .env, nada hardcoded).
# Em dev liberamos geral p/ a rede interna acessar fácil; em prod = lista explícita + allow_all False.
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # CORS (cabeçalhos cross-origin p/ os edges/front consumirem o backend)
    "corsheaders",
    # fila async (broker no próprio banco, sem Redis)
    "django_q",
    # JWT da API pública (django-ninja-jwt) — RS256 reusa as chaves em keys/ (CONVENTION §10).
    "ninja_jwt",
    # app base do projeto
    "core.apps.CoreConfig",
    # integrações externas
    "integrations.bank.asaas.apps.AsaasConfig",
    "integrations.bank.infinitepay.apps.InfinitepayConfig",
    "integrations.tools.cep.apps.CepConfig",
    "integrations.tools.cpf.apps.CpfConfig",
    "integrations.ai.apps.AiConfig",
    # biometria facial (face-match doc×selfie com InsightFace, CPU) — checks só AVISAM (não travam boot)
    "integrations.tools.biometric.apps.BiometricConfig",
    # apps de negócio do monólito
    "notify.apps.NotifyConfig",
    # users = o "quem" (identidade + papéis + dados pessoais). auth/jwt/otp/profiles/roles vivem
    # dentro dele como pacotes; um migration set só (CONVENTION §2). É o AUTH_USER_MODEL.
    "users.apps.UsersConfig",
    # finance = motor de comissão/payout (commissions + payout; fees vem depois). Consome users
    # (FK→User, pix do profile), asaas.payout (PIX-out) e notify. Pasta em inglês (Victor 2026-06-01).
    "finance.apps.FinanceConfig",
    # hub = o POLO (§4 item 5). Hub→Address (FK §4); marca = catálogo no .env. Ações do
    # coordenador entram depois (grupo leadership). Consome users (coordinator/promoter).
    "hub.apps.HubConfig",
    # Mantido temporariamente só para aplicar a migration que remove as tabelas do bot interno.
    "bot.apps.BotConfig",
]

# User custom (palavra do Victor 2026-06-01; sobrepõe o "User padrão" da CONVENTION §4): a
# identidade carrega o external_id (UUID na borda). Login é passwordless por OTP, então o
# USERNAME_FIELD é o external_id (admin/superuser loga por UUID). Definido ANTES da 1ª migração.
AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise logo após o Security (doc): serve /static/ (admin) MESMO com DEBUG=False —
    # o runserver puro só serve static com DEBUG=True (auditoria front 2026-06-11, item DEBUG).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # CorsMiddleware o mais alto possível, antes do CommonMiddleware (doc django-cors-headers).
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # ponytail: logging estruturado (request_id + method/path/status/duration) — após Common.
    "core.logging_middleware.RequestLoggingMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # dev -> SQLite (default); prod -> PostgreSQL via DATABASE_URL no .env.
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
}
# Conexões persistentes: o poll do wizard (um GET a cada poucos segundos POR candidato) pagava
# handshake+auth do Postgres em todo request. Health check evita reusar conexão morta (Django 5).
DATABASES["default"]["CONN_MAX_AGE"] = env.int("DB_CONN_MAX_AGE", default=60)
DATABASES["default"]["CONN_HEALTH_CHECKS"] = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
# Destino do collectstatic; o WhiteNoise serve daqui (admin funciona com DEBUG=False).
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media (arquivos servidos) — CONVENTION §6 (Django expõe /media/).
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Limite de upload de imagem dos documentos (users/documents) — config, não hardcoded (§10).
MAX_UPLOAD_MB = env.int("MAX_UPLOAD_MB", default=10)

# Análises assíncronas por IA (users.roles._analysis — RG, selfie): TTL e cadência de polling do
# front (proposta API #2). TTL = quanto a gente espera o worker antes de jogar o `pending` em
# `review` (nunca fica "analisando…" eterno se a task morreu). POLL = de quanto em quanto o front
# volta a perguntar. Config, não hardcoded (§10).
# 300s (Victor 2026-06-17): o pipeline real do RG mede ~35s ponta-a-ponta (visão+OCR+extração com IA),
# então 300s só dispara pra task GENUINAMENTE morta — fecha a janela do "worker zumbi" (vivo, mas lento,
# que terminaria e sobrescreveria uma decisão já tomada). O guard em `_rg_extract_and_finish` cobre o resto.
ANALYSIS_TTL_SECONDS = env.int("ANALYSIS_TTL_SECONDS", default=300)
ANALYSIS_POLL_MS = env.int("ANALYSIS_POLL_MS", default=2500)


# Biometria facial (integrations.tools.biometric) — face-match doc×selfie com InsightFace (ArcFace, CPU). §8/§10.
# BIOMETRIC_ENABLED liga/desliga o gate no funil (dev sem o modelo → desligar p/ não jogar tudo em review).
# O modelo carrega PREGUIÇOSO (1º uso); os system checks só AVISAM (não travam o boot — biometria é apoio).
# ⚠️ THRESHOLDS: são do COSSENO do ArcFace (~0.2–0.7, mesma pessoa ~0.4–0.7), NÃO a escala de "%" de APIs
# comerciais. O 0.90/0.80 sugerido pelo Victor é de outra escala — default no padrão do buffalo_l e a
# gente CALIBRA com pares reais no teste (Portão 3), ajustando aqui no .env sem mexer no código.
BIOMETRIC_ENABLED = env.bool("BIOMETRIC_ENABLED", default=True)
BIOMETRIC_MODEL_NAME = env("BIOMETRIC_MODEL_NAME", default="buffalo_l")
# Pesos do modelo (~298MB) ficam FORA do backend/ (repo git) — em <mvp>/models/insightface — pra não
# virar bloat/commit. Em prod aponte pra um volume persistente no .env. Baixa sozinho no 1º uso se faltar.
BIOMETRIC_MODEL_ROOT = env(
    "BIOMETRIC_MODEL_ROOT", default=str(BASE_DIR.parent / "models" / "insightface")
)
# Calibrado com par REAL 2026-06-05 (CNH×selfie mesma pessoa ≈0.42; pessoas diferentes <0.21). O .env manda.
BIOMETRIC_MATCH_THRESHOLD = env.float("BIOMETRIC_MATCH_THRESHOLD", default=0.35)
BIOMETRIC_REVIEW_THRESHOLD = env.float("BIOMETRIC_REVIEW_THRESHOLD", default=0.28)
BIOMETRIC_LIVENESS_PROVIDER = env("BIOMETRIC_LIVENESS_PROVIDER", default="local")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Asaas (integrations.bank.asaas) — config via .env (CONVENTION §8/§10).
# Sem a key o app ainda sobe, mas o system check asaas.E001 erra em vermelho no boot.
# A api-key do Asaas começa com "$" ($aact_...), e o django-environ trata "$" como proxy de
# variável (quebraria o settings). Por isso lemos via os.environ (valor literal) — read_env()
# já populou os.environ acima. Centralizado aqui no settings, ninguém usa os.environ espalhado.
ASAAS_API_KEY = os.environ.get("ASAAS_API_KEY", "")
ASAAS_BASE_URL = env("ASAAS_BASE_URL", default="https://api.asaas.com")
# Token do webhook (= authToken do `asaas-access-token`, NÃO é HMAC — o Asaas não tem HMAC) e URL
# externa, usados a partir do 1a-ii/1a-iii. Hex/URL, sem "$" (lê via env normal). Um token só pros
# dois endpoints que o Asaas chama de volta: webhook de eventos e mecanismo de validação de saque.
ASAAS_WEBHOOK_SECRET = env("ASAAS_WEBHOOK_SECRET", default="")
EXTERNAL_URL = env("EXTERNAL_URL", default="")
# Base do link de divulgação do promotor (ref_url). Vazio => cai no EXTERNAL_URL (= backend → 404).
# Sem esta linha o valor do .env é ignorado pelo getattr(settings, "LANDING_BASE_URL", "") em ref_url().
LANDING_BASE_URL = env("LANDING_BASE_URL", default="")
# URL do front pra onde o gateway redireciona APÓS o pagamento (cartão/PIX). Vazio => cai no EXTERNAL_URL.
# «PENDÊNCIA»: Victor define a URL real do front.
FRONTEND_URL = env("FRONTEND_URL", default="")
# Path do wizard de matrícula no front — vira o deep-link dos notifies de resolução (proposta API #11:
# o coordenador decide → o aluno recebe o link e volta direto pro passo certo). Sem FRONTEND_URL → sem link.
ENROLLMENT_RESUME_PATH = env("ENROLLMENT_RESUME_PATH", default="/matricula")
# URL de login da instituição parceira (SIGA) — vai no notify de credenciais quando o cliente
# vira ALUNO (login/senha/link). A partir daí é a única coisa que ele recebe (Victor 2026-06-23).
INSTITUTION_LOGIN_URL = env(
    "INSTITUTION_LOGIN_URL", default="https://cbi.sistemasiga.net/login/"
)
# Prazo default (dias) da cobrança PIX quando o caller não passa due_date.
ASAAS_CHARGE_DUE_DAYS = env.int("ASAAS_CHARGE_DUE_DAYS", default=3)
# Onboarding/auto-cadastro do webhook (1a-v): nome do webhook que gerenciamos no Asaas (casamos por
# URL; o nome é só fallback) e TTL (segundos) do nonce de verificação da URL pública.
ASAAS_WEBHOOK_NAME = env("ASAAS_WEBHOOK_NAME", default="dmz-asaas-managed")
URL_VERIFY_NONCE_TTL = env.int("URL_VERIFY_NONCE_TTL", default=600)


# InfinitePay (integrations.bank.infinitepay) — config via .env (CONVENTION §8/§10).
# A InfinitePay NÃO usa api-key: autentica só pelo `handle` (InfiniteTag) — quem recebe é o dono da
# conta, não há segredo no envio. Sem o handle, o system check infinitepay.E001 trava o boot. O handle
# às vezes é colado com "$" à esquerda (InfiniteTag); removemos pra não furar a chamada. Lemos via
# os.environ por simetria com a key do asaas (read_env() já populou os.environ acima).
INFINITEPAY_HANDLE = os.environ.get("INFINITEPAY_HANDLE", "").lstrip("$")
# API de Checkout atual: api.checkout.infinitepay.io (paths /links e /payment_check). O endpoint antigo
# api.infinitepay.io/invoices/public/checkout/* foi descontinuado — mesma lógica, só a URL mudou.
INFINITEPAY_BASE_URL = env(
    "INFINITEPAY_BASE_URL", default="https://api.checkout.infinitepay.io"
)
INFINITEPAY_HTTP_TIMEOUT = env.float("INFINITEPAY_HTTP_TIMEOUT", default=10.0)
# URL de sucesso pós-pagamento (opcional; default = EXTERNAL_URL no serviço de checkout).
INFINITEPAY_REDIRECT_URL = env("INFINITEPAY_REDIRECT_URL", default="")


# ViaCEP (integrations.tools.cep) — lookup de CEP. API pública, sem api-key: só URL e timeout,
# config no .env (CONVENTION §8/§10, nunca hardcoded).
VIACEP_BASE_URL = env("VIACEP_BASE_URL", default="https://viacep.com.br")
VIACEP_TIMEOUT_SECONDS = env.float("VIACEP_TIMEOUT_SECONDS", default=5.0)


# CPFHub (integrations.tools.cpf) — lookup de identidade por CPF (server-side only). §8/§10.
# Tem api-key (header x-api-key). A key é hex (sem "$"), então env() normal serve (a do Asaas
# começa com "$" e exigiu os.environ). Sem a key o check cpf.W001 só AVISA (não trava — tool de apoio).
CPFHUB_API_KEY = env("CPFHUB_API_KEY", default="")
CPFHUB_BASE_URL = env("CPFHUB_BASE_URL", default="https://api.cpfhub.io")
CPFHUB_TIMEOUT = env.float("CPFHUB_TIMEOUT", default=5.0)


# IA (integrations.ai) — engine LLM multi-provider OpenAI-compatible + fallback (CONVENTION §8/§10).
# Todos os providers (deepseek, dashscope, groq, openai, openrouter, nvidia, …) falam o mesmo
# protocolo: cada um precisa só de IA_<NAME>_BASE_URL + IA_<NAME>_API_KEY. Somar um novo é só .env.
# As keys têm chars variados (pontos, hifens) → lemos via os.environ (read_env() já populou acima),
# como no Asaas. IA_FALLBACK_CHAIN="provider:model,..." define a ORDEM de tentativa (1º = default);
# falha rede/timeout/429/5xx cai pro próximo. Config incompleta => check ai.E001/E002/E003 trava o boot.
IA_PROVIDERS = {}
for _ia_name in env.list("IA_PROVIDERS", default=[]):
    _ia_name = _ia_name.strip().lower()
    _ia_base = os.environ.get(f"IA_{_ia_name.upper()}_BASE_URL", "")
    _ia_key = os.environ.get(f"IA_{_ia_name.upper()}_API_KEY", "")
    if _ia_base and _ia_key:
        IA_PROVIDERS[_ia_name] = {"base_url": _ia_base, "api_key": _ia_key}

IA_FALLBACK_CHAIN = []
for _ia_item in env.list("IA_FALLBACK_CHAIN", default=[]):
    if ":" in _ia_item:
        _ia_p, _, _ia_m = _ia_item.partition(":")
        IA_FALLBACK_CHAIN.append((_ia_p.strip(), _ia_m.strip()))

IA_DEFAULT_TEMPERATURE = env.float("IA_DEFAULT_TEMPERATURE", default=0.3)
IA_MAX_TOKENS = env.int("IA_MAX_TOKENS", default=0)
IA_TIMEOUT = env.float("IA_TIMEOUT", default=60.0)
# Modelo multimodal do gateway OmniRoute para VISÃO (describe_image via /v1/chat/completions). Vazio
# => o primário OmniRoute é pulado e a visão vai direto pro MiniMax-M3 (fallback sempre presente).
IA_OMNIROUTE_VISION_MODEL = env("IA_OMNIROUTE_VISION_MODEL", default="")

# IA — tabela de preços OPCIONAL (integrations.ai.pricing). Formato: "provider:model:in:out, ..."
# (in/out = preço por 1 MILHÃO de tokens, moeda à escolha do Victor). VAZIO por padrão → AiCall.cost
# segue null (§8: não invento dinheiro). Entrada malformada é ignorada (não derruba o boot).
IA_PRICES = {}
for _ia_price in env.list("IA_PRICES", default=[]):
    _pp = [_s.strip() for _s in _ia_price.split(":")]
    if len(_pp) == 4:
        try:
            from decimal import Decimal as _Dec

            IA_PRICES[(_pp[0], _pp[1])] = (_Dec(_pp[2]), _Dec(_pp[3]))
        except (ArithmeticError, ValueError):
            pass

# IA — modalidades de mídia (integrations.ai), via REST httpx. São OPCIONAIS: sem a key o check só
# AVISA (ai.W001/W002/W003), não trava como a cadeia LLM (que é o núcleo). Keys AIza/sk_ (sem "$").
# Gemini = STT; Google Vision = OCR.
GEMINI_API_KEY = env("GEMINI_API_KEY", default="")
GEMINI_BASE_URL = env(
    "GEMINI_BASE_URL", default="https://generativelanguage.googleapis.com/v1beta"
)
# STT (transcrição de áudio das submissões de treino).
GEMINI_STT_MODEL = env("GEMINI_STT_MODEL", default="gemini-3-flash-preview")

GOOGLE_VISION_API_KEY = env("GOOGLE_VISION_API_KEY", default="")
GOOGLE_VISION_BASE_URL = env(
    "GOOGLE_VISION_BASE_URL", default="https://vision.googleapis.com"
)
# Alternativa de auth (prod, mais robusto): path pro JSON do service-account. Vazio => usa a api-key.
GOOGLE_VISION_SERVICE_ACCOUNT_JSON = env(
    "GOOGLE_VISION_SERVICE_ACCOUNT_JSON", default=""
)

# MiniMax — visão (descrever imagem com MiniMax-M3).
MINIMAX_API_KEY = env("MINIMAX_API_KEY", default=env("IA_MINIMAX_API_KEY", default=""))
MINIMAX_BASE_URL = env("MINIMAX_BASE_URL", default="https://api.minimax.io")
MINIMAX_VISION_MODEL = env("MINIMAX_VISION_MODEL", default="MiniMax-M3")
# MiniMax DIRETO (fallback sem gateway) — o MiniMaxClient(direct=True) lê estes; sem eles o "direto"
# desabava no MINIMAX_BASE_URL (o gateway), anulando o "zero single-point-of-failure" do .env.
MINIMAX_DIRECT_API_KEY = env("MINIMAX_DIRECT_API_KEY", default="")
MINIMAX_DIRECT_BASE_URL = env(
    "MINIMAX_DIRECT_BASE_URL", default="https://api.minimax.io"
)

# Gemini também serve a cadeia LLM (fallback) via endpoint OpenAI-compatible do Google — REUSA a
# GEMINI_API_KEY (sem duplicar key no .env). Entra como provider "gemini" quando está na cadeia.
if GEMINI_API_KEY and any(_p == "gemini" for _p, _m in IA_FALLBACK_CHAIN):
    IA_PROVIDERS.setdefault(
        "gemini",
        {
            "base_url": env(
                "IA_GEMINI_LLM_BASE_URL",
                default="https://generativelanguage.googleapis.com/v1beta/openai",
            ),
            "api_key": GEMINI_API_KEY,
        },
    )


# Segredo de serviço do bot externo e das ferramentas internas.
# Fail-closed: vazio no .env => a rota sem-OTP recusa (o segredo é a prova de identidade, não a rede).
BOT_SERVICE_SECRET = env("BOT_SERVICE_SECRET", default="")
BOT_SERVICE_HEADER = env("BOT_SERVICE_HEADER", default="x-bot-service-token")
# Wave1 hardening — consumido por api/tools (allowlist DMZ) e pelo serve de mídia privada.
# TOOLS_ALLOWED_IPS aceita IPs e CIDRs (o gate usa o módulo ipaddress). Default = loopback + rede interna.
TOOLS_ALLOWED_IPS = env.list(
    "TOOLS_ALLOWED_IPS", default=["127.0.0.1", "::1", "10.0.0.0/8"]
)
# Nº de proxies CONFIÁVEIS na frente do app (nginx/Caddy). O gate por IP (core.net.client_ip) conta
# esse tanto de hops a partir da DIREITA do X-Forwarded-For — o XFF esquerdo é forjável pelo cliente
# e NUNCA decide acesso. Default 1 (um reverse-proxy). Ajuste se houver cadeia de proxies confiáveis.
TRUSTED_PROXY_COUNT = env.int("TRUSTED_PROXY_COUNT", default=1)
# Prefixos de mídia que exigem autorização (dono do recurso). O resto (training/IA) é público.
# `audit`: recortes de rosto (selfie/RG) da auditoria da IA (enrollment/service.py) — PII de rosto;
# são internos (nenhum front os consome), então sem dono resolvível caem em revisor-only (fail-closed).
# ⚠ Se o .env de prod SOBRESCREVER esta lista, inclua `audit` lá também.
MEDIA_PRIVATE_PREFIXES = env.list(
    "MEDIA_PRIVATE_PREFIXES",
    default=["documents", "selfie", "diploma", "receipt", "student", "audit"],
)
# notify-server é a única implementação de notificações.
NOTIFY_SERVER_URL = env("NOTIFY_SERVER_URL", default="http://notify.v7m.org")
NOTIFY_API_KEY = os.environ.get("NOTIFY_API_KEY", "")
NOTIFY_TIMEOUT = env.float("NOTIFY_TIMEOUT", default=10.0)
NOTIFY_SYNC_TIMEOUT = env.float("NOTIFY_SYNC_TIMEOUT", default=60.0)


# Django-Q2 — fila async com broker no próprio banco (sem Redis). `qcluster` roda o worker.
Q_CLUSTER = {
    "name": "mvp",
    "orm": "default",
    # timeout precisa cobrir o PIOR caso real da task (cadeia de visão com fallback + OCR +
    # extração passa fácil de 90s com provider lento) — senão o worker é morto no meio e a
    # task re-entra; retry SEMPRE > timeout; max_attempts corta a task-veneno (sem ele o
    # django-q2 re-entrega para sempre, queimando worker e crédito de IA).
    "timeout": env.int("Q_TIMEOUT", default=240),
    "retry": env.int("Q_RETRY", default=300),
    "max_attempts": env.int("Q_MAX_ATTEMPTS", default=3),
    # `workers` baixo de propósito: cada worker carrega o modelo InsightFace (~300MB) no 1º uso de
    # biometria. O default do Django-Q (= nº de CPUs) sobe 14 workers e OOM-ava neste host (16GB,
    # ~1GB livre) durante o teste real (Victor 2026-06-16). Prod sobe via Q_WORKERS no .env.
    "workers": env.int("Q_WORKERS", default=2),
}


# users — auth (jwt, otp) · profiles · roles (CONVENTION §2/§4/§9). Config via .env (§10).
# ── JWT (users.auth.jwt): RS256, par de chaves PEM. As chaves são geradas no 1º uso se faltarem
# (users/auth/jwt/keys.py) num diretório gitignored — a privada NUNCA vai pro git. Paths relativos
# ao BASE_DIR. issuer/audience e expirações são config (defaults = porte do legado).
JWT_PRIVATE_KEY_PATH = BASE_DIR / env(
    "JWT_PRIVATE_KEY_PATH", default="keys/jwt_private.pem"
)
JWT_PUBLIC_KEY_PATH = BASE_DIR / env(
    "JWT_PUBLIC_KEY_PATH", default="keys/jwt_public.pem"
)
JWT_ALGORITHM = env("JWT_ALGORITHM", default="RS256")
JWT_ACCESS_EXPIRE_MINUTES = env.int("JWT_ACCESS_EXPIRE_MINUTES", default=30)
JWT_REFRESH_EXPIRE_MINUTES = env.int("JWT_REFRESH_EXPIRE_MINUTES", default=1440)
JWT_ISSUER = env("JWT_ISSUER", default="supletivo")
JWT_AUDIENCE = env("JWT_AUDIENCE", default="")

# django-ninja-jwt (substitui o JWT escrito à mão — Victor 2026-06-02). RS256 REUSA o mesmo par
# PEM em keys/ (lido path-based porque o objeto `settings` ainda está sendo montado aqui). Sem
# consumidor externo de JWKS → o endpoint JWKS foi removido. issue/decode em users/auth/jwt/service.
from users.auth.jwt import keys as _jwt_keys  # noqa: E402 (import tardio: precisa dos paths acima)

_JWT_PRIVATE_PEM, _JWT_PUBLIC_PEM = _jwt_keys.read_or_create_pair(
    JWT_PRIVATE_KEY_PATH, JWT_PUBLIC_KEY_PATH
)
NINJA_JWT = {
    "ALGORITHM": JWT_ALGORITHM,
    "SIGNING_KEY": _JWT_PRIVATE_PEM,
    "VERIFYING_KEY": _JWT_PUBLIC_PEM,
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=JWT_ACCESS_EXPIRE_MINUTES),
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=JWT_REFRESH_EXPIRE_MINUTES),
    "ISSUER": JWT_ISSUER or None,
    "AUDIENCE": JWT_AUDIENCE or None,
}

# ── OTP (users.auth.otp): código numérico, hash SHA256 (plaintext nunca persiste), TTL/tentativas
# e rate-limit em DB (sem Redis — Django-Q usa o banco).
# TTL ≠ cooldown (auditoria front 2026-06-11): TTL = validade do código pra DIGITAR (10 min);
# cooldown de REENVIO = WINDOW_S (60s, o `otp_wait` do check); teto horário = anti-abuso de custo
# WhatsApp, alto o bastante pra nunca trancar usuário legítimo (10/h; o caso real que trancou foi
# 5/h com a fila parada). Cada reenvio ROTACIONA o código (verify usa só o último).
OTP_TTL_S = env.int("OTP_TTL_S", default=600)
OTP_NUM_DIGITS = env.int("OTP_NUM_DIGITS", default=6)
OTP_MAX_ATTEMPTS = env.int("OTP_MAX_ATTEMPTS", default=3)
# Rate-limit por IP fica no reverse proxy (CONVENTION §5), não no app.
OTP_RATELIMIT_WINDOW_S = env.int("OTP_RATELIMIT_WINDOW_S", default=60)
OTP_RATELIMIT_HOURLY_MAX = env.int("OTP_RATELIMIT_HOURLY_MAX", default=10)
OTP_FOOTER = env("OTP_FOOTER", default="")
OTP_ACTIVE = env.bool("OTP_ACTIVE", default=True)

# ── ROLES (users.roles): catálogo de transições no .env, NÃO em DB (§9). JSON: lista de
# {from_role, to_role, mode: add|replace, requires_role?, forbids_role?, blocking?}. A tabela
# users.UserRole guarda só quem tem qual role agora + histórico. Catálogo inválido derruba o boot.
# Mudança Victor 2026-06-16: o candidato vira PROMOTOR direto (o coordenador aprova) — `training`
# deixou de ser etapa-da-cadeia e virou ROLE OVERLAY (add+blocking): adicionada/removida ao promotor
# enquanto houver matéria obrigatória pendente (a trava é lida do /me, não do JWT).
ROLE_RULES = env.json(
    "ROLE_RULES",
    default=[
        {"from_role": None, "to_role": "lead", "mode": "add"},
        {"from_role": "lead", "to_role": "enrollment", "mode": "replace"},
        {"from_role": "enrollment", "to_role": "student", "mode": "replace"},
        {
            "from_role": None,
            "to_role": "veteran",
            "mode": "add",
            "requires_role": "student",
        },
        {"from_role": None, "to_role": "candidate", "mode": "add"},
        {"from_role": "candidate", "to_role": "promoter", "mode": "replace"},
        {
            "from_role": None,
            "to_role": "training",
            "mode": "add",
            "requires_role": "promoter",
            "blocking": True,
        },
        {
            "from_role": None,
            "to_role": "coordinator",
            "mode": "add",
            "requires_role": "promoter",
        },
    ],
)

# finance (app finance) — motor de comissão/payout. Valores em REAIS (string→Decimal no finance.config,
# nunca float; só o infinitepay usa centavos). DEV mini de propósito: teste mexe DINHEIRO REAL →
# comissão 1 / bônus 5 / coord 1 / threshold 5. PROD pede ao Victor (ref 100/500/50). §8/§10.
COMMISSION_DIRECT = env("COMMISSION_DIRECT", default="1")
COMMISSION_BONUS_FLAT = env("COMMISSION_BONUS_FLAT", default="5")
COMMISSION_COORDINATOR = env("COMMISSION_COORDINATOR", default="1")
COMMISSION_BONUS_THRESHOLD = env.int("COMMISSION_BONUS_THRESHOLD", default=5)
# fechamento: dia (0=seg..4=sex) e hora em America/Sao_Paulo. O Schedule é WEEKLY (sem croniter).
COMMISSION_CLOSING_WEEKDAY = env.int("COMMISSION_CLOSING_WEEKDAY", default=4)
COMMISSION_CLOSING_HOUR = env.int("COMMISSION_CLOSING_HOUR", default=18)

# matrícula (funil do aluno, §4 itens 11/13) — preço por gateway. Victor 2026-06-07: o COBRADO é o MESMO
# EXIBIDO na vitrine (GET /clients/pricing), uma fonte só. PIX em REAIS (valor cheio); CARTÃO em CENTAVOS
# (total; o front mostra 12x). DEV: PIX R$5 / cartão R$1 (=100 centavos). PROD = pedir ao Victor (§8).
ENROLLMENT_PRICE_CARD_CENTS = env.int("ENROLLMENT_PRICE_CARD_CENTS", default=100)
ENROLLMENT_PRICE_PIX = env("ENROLLMENT_PRICE_PIX", default="5")
# Preço da AUTO-MATRÍCULA do promotor (Victor 2026-06-16: preço diferente, fluxo próprio, SEM comissão).
# DEV: default = o preço normal (mini). PROD: «PENDÊNCIA» — Victor define o valor do promotor no .env.
ENROLLMENT_PRICE_PROMOTER_CARD_CENTS = env.int(
    "ENROLLMENT_PRICE_PROMOTER_CARD_CENTS", default=ENROLLMENT_PRICE_CARD_CENTS
)
ENROLLMENT_PRICE_PROMOTER_PIX = env(
    "ENROLLMENT_PRICE_PROMOTER_PIX", default=ENROLLMENT_PRICE_PIX
)
ENROLLMENT_DESCRIPTION = env("ENROLLMENT_DESCRIPTION", default="Matrícula Supletivo")

# treino (LMS do funil do colaborador, §4 item 7) — nota de corte (0–10) p/ aprovar uma submissão da IA.
# Default 6 (palavra do dono). PROD = pedir ao Victor se mudar.
TRAINING_PASS_SCORE = env("TRAINING_PASS_SCORE", default="6")


# hub (app hub) — o POLO (§4 item 5). Marca = catálogo no .env (HUB_BRANDS), igual às roles (§9):
# validado no hub/interface, NÃO choices fixo no model. `ieadpg`→`standard` (Victor 2026-06-03).
HUB_BRANDS = env.list("HUB_BRANDS", default=["wyden", "estacio", "standard"])
DEFAULT_HUB_BRAND = env("DEFAULT_HUB_BRAND", default="standard")
# conta-mãe (seed_defaults): no início TUDO centralizado no Victor — staff (superuser) + promoter +
# coordinator do hub padrão, na MESMA conta (Victor 2026-06-03). A senha é só p/ o /admin (a API loga
# por OTP). DEV = placeholders; PROD = dados REAIS do Victor (cpf/phone só dígitos). Senha via os.environ
# (pode ter char especial), simetria com asaas/mail.
DEFAULT_STAFF_CPF = env("DEFAULT_STAFF_CPF", default="")
DEFAULT_STAFF_PHONE = env("DEFAULT_STAFF_PHONE", default="")
DEFAULT_STAFF_NAME = env("DEFAULT_STAFF_NAME", default="Staff")
DEFAULT_STAFF_EMAIL = env("DEFAULT_STAFF_EMAIL", default="")
DEFAULT_STAFF_PASSWORD = os.environ.get("DEFAULT_STAFF_PASSWORD", "")
# Chave Pix da conta-mãe — destino dos payouts dela (comissões de promotor/coordenador). O seed grava
# no Profile se estiver vazio (fecha o «rabo» "setei à mão" dos flashes de 06-06 e 06-10). Sem validação
# DICT aqui: é seed de sistema; a chave já foi provada em payout real.
DEFAULT_STAFF_PIX = env("DEFAULT_STAFF_PIX", default="")

# ── Logging estruturado (structlog) ──────────────────────────────────────────
# ponytail: structlog já está no pyproject.toml. Config mínima: console em dev, JSON em prod.
import structlog  # noqa: E402 — import perto da sua config (deliberado), não no topo


def _scrub_pii(_, __, event_dict: dict) -> dict:
    """Defesa em profundidade: mascara cpf/phone em event_dict (exception paths podem escapar
    da truncagem manual). Fail-open — nunca trava o log."""
    for k in ("cpf", "phone", "phone_resolved", "recipient_phone", "recipient_email"):
        if k in event_dict and event_dict[k]:
            v = str(event_dict[k])
            event_dict[k] = f"***{v[-2:]}" if len(v) >= 2 else "***"
    return event_dict


_structlog_processors = [
    structlog.stdlib.add_log_level,
    structlog.processors.TimeStamper(fmt="iso"),
    _scrub_pii,  # mascara PII antes do renderer
]
if DEBUG:
    _structlog_processors.append(structlog.dev.ConsoleRenderer())
else:
    _structlog_processors.append(structlog.processors.JSONRenderer())

structlog.configure(
    processors=_structlog_processors,
    wrapper_class=structlog.stdlib.BoundLogger,
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)

# ── Sentry / GlitchTip (opcional — sem DSN = no-op) ──────────────────────────
# A lógica (scrub de PII, fail-closed, no-op sem DSN) mora em `core/sentry.py` e é testada em
# `tests/test_sentry.py` — aqui só a config (§10), como no `resolve_environment` acima.
# SENTRY_ENVIRONMENT default = APP_ENV: o ambiente já é resolvido/validado ali em cima (prod,
# staging, preview, test), então repetir a informação no .env só criaria chance de divergir —
# um erro do staging carimbado "prod" no painel. O override existe pra quem roda mais de um
# deploy no MESMO APP_ENV (ex.: "staging-v7m" e "staging-qa") e precisa separar os dois.
# SENTRY_RELEASE se resolve sozinho: vazio => o SHA do HEAD do checkout, que o `deploy.yml`
# deixa exatamente no commit validado pelo CI (`git reset --hard <sha>`). Ou seja, "esse erro
# começou em qual deploy?" já responde sem ninguém editar .env a cada subida. O env var existe
# como override (build sem git, imagem de container). Só consulta o git quando HÁ DSN — em
# dev/CI, onde o Sentry está desligado, nem o subprocesso roda.
SENTRY_DSN = env("SENTRY_DSN", default="")
SENTRY_ENVIRONMENT = env("SENTRY_ENVIRONMENT", default=APP_ENV)
SENTRY_RELEASE = env("SENTRY_RELEASE", default="")
SENTRY_TRACES_SAMPLE_RATE = env.float("SENTRY_TRACES_SAMPLE_RATE", default=0.1)
# Corpo do request no evento: "never" (default) o mantém FORA — o funil dá POST de cpf/telefone/
# pix e o `send_default_pii=False` do SDK não cobre o corpo. Afrouxe só em dev/staging.
SENTRY_REQUEST_BODY = env("SENTRY_REQUEST_BODY", default="never")

from core.sentry import (  # noqa: E402 — import perto da sua config (padrão do structlog acima)
    git_sha,
    init_sentry,
)

if SENTRY_DSN and not SENTRY_RELEASE:
    SENTRY_RELEASE = git_sha(BASE_DIR)

SENTRY_ENABLED = init_sentry(
    dsn=SENTRY_DSN,
    environment=SENTRY_ENVIRONMENT,
    release=SENTRY_RELEASE,
    traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
    request_body=SENTRY_REQUEST_BODY,
)
