# Generated by Django 6.0.3 on 2026-04-06 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionApiLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(blank=True, help_text='Operacao executada na integracao', max_length=120, null=True)),
                ('request_method', models.CharField(blank=True, help_text='Metodo HTTP da chamada', max_length=10, null=True)),
                ('endpoint', models.CharField(blank=True, help_text='Endpoint ou URL acessada', max_length=500, null=True)),
                ('instance', models.CharField(blank=True, help_text='Instancia Evolution utilizada', max_length=120, null=True)),
                ('target_number', models.CharField(blank=True, help_text='Numero principal do fluxo', max_length=40, null=True)),
                ('success', models.BooleanField(default=False)),
                ('status_code', models.PositiveIntegerField(blank=True, help_text='Status HTTP retornado', null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Duracao da operacao em milissegundos', null=True)),
                ('request_data', models.JSONField(blank=True, help_text='Dados enviados na requisicao', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Dados recebidos na resposta', null=True)),
                ('response_text', models.TextField(blank=True, help_text='Resposta textual ou resumo do retorno', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro capturada', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log Evolution API',
                'verbose_name_plural': 'Logs Evolution API',
                'ordering': ['-created_at'],
            },
        ),
    ]
