# Generated by Django 5.2.14 on 2026-06-01 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "external_reference",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "payee_role",
                    models.CharField(
                        choices=[
                            ("promoter", "promotor"),
                            ("coordinator", "coordenador"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("week_of", models.DateField(db_index=True)),
                ("pix_key", models.CharField(blank=True, max_length=140, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "na fila"),
                            ("awaiting_pix", "sem chave PIX"),
                            ("submitted", "enviada"),
                            ("awaiting_balance", "sem saldo"),
                            ("paid", "paga"),
                            ("failed", "falhou"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "asaas_payment_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "asaas_status",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=7)),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "payee_role",
                    models.CharField(
                        choices=[
                            ("promoter", "promotor"),
                            ("coordinator", "coordenador"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("lead", "lead pagou"),
                            ("veteran", "student→veteran"),
                            ("bonus", "bônus de meta"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("source_external_id", models.UUIDField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pendente"),
                            ("processed", "processada"),
                            ("paid", "paga"),
                            ("failed", "falhou"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions",
                        to="finance.paymentrequest",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_type", "source_external_id"),
                        name="uniq_commission_source",
                    )
                ],
            },
        ),
    ]
