# Generated by Django 5.2.14 on 2026-06-01 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="kind",
            field=models.CharField(
                choices=[("commission", "comissão"), ("fee", "despesa")],
                db_index=True,
                default="commission",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="method",
            field=models.CharField(
                choices=[
                    ("pix_key", "PIX por chave"),
                    ("pix_qrcode", "PIX por QR code"),
                ],
                default="pix_key",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="qrcode_payload",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="supplier_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="payee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="payee_role",
            field=models.CharField(
                blank=True,
                choices=[("promoter", "promotor"), ("coordinator", "coordenador")],
                db_index=True,
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="week_of",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
