# Generated by Django 5.2.14 on 2026-06-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_paymentrequest_source_external_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="boleto_line",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="receipt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("commission", "comissão"),
                    ("fee", "despesa"),
                    ("manual", "avulso"),
                ],
                db_index=True,
                default="commission",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="method",
            field=models.CharField(
                choices=[
                    ("pix_key", "PIX por chave"),
                    ("pix_qrcode", "PIX por QR code"),
                    ("boleto", "boleto"),
                ],
                default="pix_key",
                max_length=12,
            ),
        ),
    ]
