# Generated by Django 5.2.16 on 2026-08-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_paymentrequest_boleto_line_paymentrequest_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('pending', 'pendente'), ('processed', 'processada'), ('paid', 'paga'), ('failed', 'falhou'), ('cancelled', 'cancelada')], db_index=True, default='pending', max_length=10),
        ),
    ]
