# Generated by Django 5.2.16 on 2026-08-26 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_commission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('asset', 'Ativo'), ('liability', 'Passivo'), ('equity', 'Patrimônio Líquido'), ('revenue', 'Receita'), ('expense', 'Despesa')], db_index=True, max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('payment_received', 'Recebimento de Aluno'), ('commission_accrued', 'Provisão de Comissão'), ('commission_payout', 'Pagamento de Comissão'), ('fee_payout', 'Pagamento de Taxa/Credenciador'), ('unexpected_expense', 'Custo Imprevisto'), ('manual_adjustment', 'Ajuste Manual Admin'), ('chargeback', 'Chargeback / Contestação'), ('refund', 'Reembolso / Estorno')], db_index=True, max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída'), ('failed', 'Falhou'), ('cancelled', 'Cancelada'), ('disputed', 'Em Disputa')], db_index=True, default='completed', max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('lead_payment', 'Pagamento de Lead'), ('enrollment_fee', 'Taxa de Matrícula'), ('weekly_closing', 'Fechamento Semanal'), ('manual_admin', 'Ajuste Manual do Admin'), ('unexpected', 'Custo Imprevisto'), ('dispute', 'Disputa / Chargeback'), ('gateway_sync', 'Sincronização de Gateway')], db_index=True, max_length=24)),
                ('source_external_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='kind',
            field=models.CharField(choices=[('commission', 'comissão'), ('fee', 'despesa'), ('manual', 'avulso'), ('unexpected', 'imprevisto')], db_index=True, default='commission', max_length=12),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='source_type',
            field=models.CharField(blank=True, choices=[('enrollment', 'matrícula'), ('unexpected', 'custo imprevisto'), ('manual_adjustment', 'ajuste manual')], db_index=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('manual_adjustment', 'Ajuste Manual de Saldo'), ('payout_override_pix', 'Sobrescrita de Chave PIX'), ('payout_retry', 'Forçar Retentativa de Payout'), ('payout_cancel', 'Cancelamento Soberano de Payout'), ('unexpected_expense', 'Registro de Custo Imprevisto'), ('dispute_resolution', 'Veredito de Disputa / Chargeback'), ('closing_run', 'Execução Manual de Fechamento'), ('gateway_sync', 'Sincronização Manual de Gateway')], db_index=True, max_length=32)),
                ('target_model', models.CharField(db_index=True, max_length=64)),
                ('target_external_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('justification', models.TextField()),
                ('snapshot_before', models.JSONField(blank=True, null=True)),
                ('snapshot_after', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisputeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_dispute_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('under_review', 'Em Análise pelo Admin'), ('resolved_absorbed', 'Resolvida (Prejuízo Absorvido)'), ('resolved_debited', 'Resolvida (Debitado do Promotor)'), ('resolved_contested', 'Resolvida (Contestada no Banco)'), ('cancelled', 'Cancelada')], db_index=True, default='open', max_length=24)),
                ('reason', models.TextField()),
                ('resolution', models.CharField(blank=True, choices=[('absorb_loss', 'Absorver Prejuízo na Plataforma'), ('debit_promoter', 'Descontar Comissão do Promotor'), ('contest_gateway', 'Contestar Disputa no Gateway')], max_length=24, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='finance.financialtransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entry_type', models.CharField(choices=[('debit', 'Débito'), ('credit', 'Crédito')], db_index=True, max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.financialaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.financialtransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnexpectedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('infrastructure', 'Infraestrutura e Servidores'), ('legal', 'Jurídico e Cartorial'), ('security_incident', 'Incidente de Segurança / Fraude'), ('system_failure', 'Falha de Sistema / Gateway'), ('supplier_extra', 'Custo Adicional de Fornecedor'), ('other', 'Outros Custos Operacionais')], db_index=True, max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('justification', models.TextField()),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unexpected_expenses', to='finance.paymentrequest')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_unexpected_expenses', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unexpected_expenses', to='finance.financialtransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
