# Generated by Django 5.2.16 on 2026-09-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_financialaccount_financialtransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='source_type',
            field=models.CharField(choices=[('lead', 'lead pagou'), ('veteran', 'student→veteran'), ('bonus', 'bônus de meta'), ('manual', 'avulso / manual')], db_index=True, max_length=10),
        ),
    ]
