# Generated by Django 6.0.3 on 2026-04-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='media_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='nome do arquivo da mídia'),
        ),
        migrations.AddField(
            model_name='notification',
            name='media_mime_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='mime type da mídia'),
        ),
        migrations.AddField(
            model_name='notification',
            name='media_payload',
            field=models.TextField(blank=True, default='', help_text='Base64 puro ou URL pública da mídia opcional.', verbose_name='payload da mídia'),
        ),
    ]
