# Generated by Django 5.2.14 on 2026-06-01 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="CEP"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="logradouro"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="número"
                    ),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="complemento",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="bairro"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="cidade"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="UF"
                    ),
                ),
                (
                    "country",
                    models.CharField(default="BR", max_length=2, verbose_name="país"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "endereço",
                "verbose_name_plural": "endereços",
                "db_table": "users_address",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="data de nascimento"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="nome"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="pix_key",
            field=models.CharField(
                blank=True, max_length=140, null=True, verbose_name="chave Pix"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to="users.address",
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "documento",
                "verbose_name_plural": "documentos",
                "db_table": "users_document",
            },
        ),
        migrations.CreateModel(
            name="CNH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="número"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="categoria"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de nascimento"
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(blank=True, null=True, verbose_name="validade"),
                ),
                (
                    "national_register",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="registro nacional",
                    ),
                ),
                (
                    "front_photo",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="foto frente",
                    ),
                ),
                (
                    "back_photo",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="foto verso"
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cnh",
                        to="users.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "CNH",
                "verbose_name_plural": "CNHs",
                "db_table": "users_document_cnh",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nascimento", "nascimento"),
                            ("casamento", "casamento"),
                            ("obito", "óbito"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="número"
                    ),
                ),
                (
                    "registry_office",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="cartório"
                    ),
                ),
                (
                    "book",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="livro"
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="folha"
                    ),
                ),
                (
                    "entry",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="termo"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de emissão"
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="foto"
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="users.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "certidão",
                "verbose_name_plural": "certidões",
                "db_table": "users_document_certificate",
            },
        ),
        migrations.CreateModel(
            name="Military",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="número"
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="série"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="categoria"
                    ),
                ),
                (
                    "ra",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="RA"
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="foto"
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="military",
                        to="users.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento militar",
                "verbose_name_plural": "documentos militares",
                "db_table": "users_document_military",
            },
        ),
        migrations.CreateModel(
            name="RG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="número"
                    ),
                ),
                (
                    "issuing_agency",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="órgão emissor",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de emissão"
                    ),
                ),
                (
                    "front_photo",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="foto frente",
                    ),
                ),
                (
                    "back_photo",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="foto verso"
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rg",
                        to="users.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "RG",
                "verbose_name_plural": "RGs",
                "db_table": "users_document_rg",
            },
        ),
    ]
