# Generated by Django 5.2.14 on 2026-06-04 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_address_profile_birth_date_profile_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("captured", "captado"),
                            ("waiting", "aguardando checkout"),
                            ("checkout", "em checkout"),
                            ("completed", "pago"),
                            ("failed", "falhou"),
                        ],
                        db_index=True,
                        default="captured",
                        max_length=12,
                    ),
                ),
                (
                    "failed_reason",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "promoter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="captured_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "lead",
                "verbose_name_plural": "leads",
                "db_table": "users_lead",
            },
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("credit_card", "cartão de crédito"), ("pix", "PIX")],
                        max_length=12,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("asaas", "Asaas"), ("infinitepay", "InfinitePay")],
                        max_length=12,
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "checkout_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("receipt_url", models.URLField(blank=True, max_length=500, null=True)),
                ("qrcode_payload", models.TextField(blank=True, null=True)),
                (
                    "qrcode_image",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_paid", models.BooleanField(db_index=True, default=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout",
                        to="users.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "checkout do lead",
                "verbose_name_plural": "checkouts do lead",
                "db_table": "users_lead_checkout",
            },
        ),
    ]
