# Generated by Django 5.2.14 on 2026-06-04 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0001_initial"),
        ("users", "0003_lead_checkout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "aguardando pagamento"),
                    ("paid", "pago"),
                    ("failed", "falhou"),
                ],
                db_index=True,
                default="pending",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "iniciada"),
                            ("profile", "perfil"),
                            ("address", "endereço"),
                            ("documents", "documentos"),
                            ("education", "dados escolares"),
                            ("selfie", "selfie"),
                            ("awaiting_release", "aguardando liberação"),
                            ("completed", "concluída"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=20,
                    ),
                ),
                ("study_platform", models.JSONField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="hub.hub",
                    ),
                ),
                (
                    "promoter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments_promoted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "matrícula",
                "verbose_name_plural": "matrículas",
                "db_table": "users_enrollment",
            },
        ),
        migrations.CreateModel(
            name="EducationalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_year_studied",
                    models.CharField(
                        max_length=64, verbose_name="último ano/série cursado"
                    ),
                ),
                (
                    "last_year_when",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="quando"
                    ),
                ),
                (
                    "last_school",
                    models.CharField(max_length=255, verbose_name="qual escola"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educational_data",
                        to="users.enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "dados escolares",
                "verbose_name_plural": "dados escolares",
                "db_table": "users_enrollment_education",
            },
        ),
    ]
