# Generated by Django 5.2.14 on 2026-06-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_lead_status_enrollment_educationaldata"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="birthplace",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="father_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="marital_status",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="mother_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="nationality",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="selfie_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="selfie_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="selfie_verified",
            field=models.BooleanField(default=False),
        ),
    ]
