# Generated by Django 5.2.14 on 2026-06-04 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0001_initial"),
        ("users", "0005_enrollment_birthplace_enrollment_father_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("text_content", models.TextField()),
                ("question", models.TextField()),
                ("expected_answer", models.TextField()),
                ("video", models.CharField(blank=True, max_length=255, null=True)),
                ("photo", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "matéria do treino",
                "verbose_name_plural": "matérias do treino",
                "db_table": "users_training_material",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "iniciado"),
                            ("profile", "perfil"),
                            ("address", "endereço"),
                            ("documents", "documentos"),
                            ("pix", "chave pix"),
                            ("selfie", "selfie"),
                            ("completed", "concluído"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=12,
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("birthplace", models.CharField(blank=True, max_length=128, null=True)),
                ("nationality", models.CharField(blank=True, max_length=64, null=True)),
                ("pix_key", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "pix_key_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("pix_validated", models.BooleanField(default=False)),
                (
                    "selfie_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("selfie_verified", models.BooleanField(default=False)),
                ("selfie_description", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="hub.hub",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "candidato",
                "verbose_name_plural": "candidatos",
                "db_table": "users_candidate",
            },
        ),
        migrations.CreateModel(
            name="Promoter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "ativo"), ("suspended", "suspenso")],
                        db_index=True,
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promoters",
                        to="hub.hub",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promoter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "promotor",
                "verbose_name_plural": "promotores",
                "db_table": "users_promoter",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("answer", models.TextField()),
                (
                    "grade",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("justification", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "corrigindo"),
                            ("approved", "aprovada"),
                            ("rejected", "reprovada"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="users.material",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "submissão do treino",
                "verbose_name_plural": "submissões do treino",
                "db_table": "users_training_submission",
            },
        ),
        migrations.CreateModel(
            name="Trainee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "em treino"),
                            ("awaiting_interview", "aguardando entrevista"),
                            ("approved", "aprovado"),
                            ("rejected", "rejeitado"),
                        ],
                        db_index=True,
                        default="training",
                        max_length=20,
                    ),
                ),
                ("awaiting_interview_at", models.DateTimeField(blank=True, null=True)),
                ("decision_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainees_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "trainee",
                "verbose_name_plural": "trainees",
                "db_table": "users_trainee",
            },
        ),
    ]
