# Generated by Django 5.2.14 on 2026-06-04 21:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0001_initial"),
        ("users", "0006_material_candidate_promoter_submission_trainee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_documents", "aguardando documentos"),
                            ("documents_under_review", "documentos em análise (IA)"),
                            ("exam_released", "liberado para agendar a prova"),
                            ("exam_scheduled", "prova agendada"),
                            ("exam_failed", "reprovado na prova (refazer)"),
                            (
                                "awaiting_documentation_dispatch",
                                "aguardando envio de documentação",
                            ),
                            ("pending", "com pendência"),
                            (
                                "awaiting_diploma_issuance",
                                "aguardando emissão do diploma",
                            ),
                            ("awaiting_pickup", "aguardando retirada"),
                            ("veteran", "veterano"),
                        ],
                        db_index=True,
                        default="awaiting_documents",
                        max_length=40,
                    ),
                ),
                (
                    "platform_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "platform_login",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "platform_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("platform_notes", models.TextField(blank=True, null=True)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="hub.hub",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "aluno",
                "verbose_name_plural": "alunos",
                "db_table": "users_student",
            },
        ),
        migrations.CreateModel(
            name="StudentDiploma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pickup_photo",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "commission_triggered_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diplomas_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diploma",
                        to="users.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "diploma",
                "verbose_name_plural": "diplomas",
                "db_table": "users_student_diploma",
            },
        ),
        migrations.CreateModel(
            name="StudentExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("subject", models.CharField(max_length=120, verbose_name="matéria")),
                ("scheduled_at", models.DateTimeField(verbose_name="agendada para")),
                (
                    "attempt_number",
                    models.PositiveIntegerField(default=1, verbose_name="tentativa"),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "aprovado"), ("failed", "reprovado")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("corrected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="observações",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "corrected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams_corrected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="users.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "prova do aluno",
                "verbose_name_plural": "provas do aluno",
                "db_table": "users_student_exam",
            },
        ),
        migrations.CreateModel(
            name="StudentPendency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("document", "documentação"),
                            ("fee", "taxa/comissão"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("amount_cents", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fee_request_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pendencies_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pendencies",
                        to="users.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "pendência do aluno",
                "verbose_name_plural": "pendências do aluno",
                "db_table": "users_student_pendency",
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("military_service", "serviço militar (só homens)"),
                            ("certificate", "certificado do último ano"),
                            ("transcript", "histórico escolar"),
                            ("blood_type", "tipo sanguíneo (foto)"),
                            ("address_proof", "comprovante de endereço (foto)"),
                            ("id_card", "documento pessoal / RG (foto)"),
                            ("birth_certificate", "certidão"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="foto"
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "aguardando IA"),
                            ("approved", "aprovado pela IA"),
                            ("rejected", "reprovado pela IA"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validation_result", models.JSONField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="users.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento do aluno",
                "verbose_name_plural": "documentos do aluno",
                "db_table": "users_student_document",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "doc_type"), name="uniq_student_doc_type"
                    )
                ],
            },
        ),
    ]
