# Generated by Django 5.2.14 on 2026-06-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_student_studentdiploma_studentexam_studentpendency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="short_token",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
