# Generated by Django 5.2.14 on 2026-06-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_checkout_short_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
