# Generated by Django 5.2.14 on 2026-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_studentdocument_validation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="selfie_status",
            field=models.CharField(
                choices=[
                    ("pending", "aguardando IA"),
                    ("approved", "aprovada"),
                    ("rejected", "reprovada (refazer)"),
                    ("review", "em revisão (coordenador decide)"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="selfie_status",
            field=models.CharField(
                choices=[
                    ("pending", "aguardando IA"),
                    ("approved", "aprovada"),
                    ("rejected", "reprovada (refazer)"),
                    ("review", "em revisão (coordenador decide)"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
