# Generated by Django 5.2.14 on 2026-06-05 12:23
# Editada à mão: preserva o vínculo OtpCode.notification_external_id (UUID) -> FK `notification`
# ANTES de remover a coluna antiga (cria a FK, copia, depois remove). studentpendency.fee_request_id
# é dormente (sem linhas) — vira FK sem migração de dados.

import uuid

import django.db.models.deletion
from django.db import migrations, models


def copy_otp_notification(apps, schema_editor):
    """Mapeia o antigo notification_external_id (UUID) -> FK notification (não perde os logs de OTP)."""
    OtpCode = apps.get_model("users", "OtpCode")
    Notification = apps.get_model("notify", "Notification")
    for otp in OtpCode.objects.exclude(notification_external_id__isnull=True):
        notif = Notification.objects.filter(
            external_id=otp.notification_external_id
        ).first()
        if notif is not None:
            otp.notification_id = notif.id
            otp.save(update_fields=["notification"])


def restore_otp_notification(apps, schema_editor):
    """Reverso: copia a FK notification de volta pro UUID notification_external_id (não perde auditoria).

    Roda quando a coluna antiga já foi recriada (reverter RemoveField) e a FK ainda existe.
    """
    OtpCode = apps.get_model("users", "OtpCode")
    Notification = apps.get_model("notify", "Notification")
    for otp in OtpCode.objects.exclude(notification__isnull=True):
        notif = Notification.objects.filter(id=otp.notification_id).first()
        if notif is not None:
            otp.notification_external_id = notif.external_id
            otp.save(update_fields=["notification_external_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_paymentrequest_source_external_id_and_more"),
        ("notify", "0001_initial"),
        ("users", "0011_candidate_selfie_status_enrollment_selfie_status"),
    ]

    operations = [
        # OtpCode: a coluna nova (notification_id) tem nome DIFERENTE da antiga
        # (notification_external_id) → cria a FK, copia o vínculo, depois remove a antiga.
        migrations.AddField(
            model_name="otpcode",
            name="notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="notify.notification",
            ),
        ),
        migrations.RunPython(copy_otp_notification, restore_otp_notification),
        migrations.RemoveField(
            model_name="otpcode",
            name="notification_external_id",
        ),
        # StudentPendency: a FK nova (fee_request) gera a MESMA coluna fee_request_id da antiga
        # (CharField) → remove a antiga ANTES de criar a FK. Sem dados (dormente) = sem cópia.
        migrations.RemoveField(
            model_name="studentpendency",
            name="fee_request_id",
        ),
        migrations.AddField(
            model_name="studentpendency",
            name="fee_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finance.paymentrequest",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="external_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
