# Generated by Django 5.2.14 on 2026-06-11 08:48
# Editada à mão: além do AlterField (choices), MAPEIA os dados pro vocabulário novo do wizard
# (auditoria do front 2026-06-11). Semântica antiga = "última seção concluída"; nova = "seção que o
# aluno preenche AGORA" → cada valor antigo vira o NOME da seção seguinte. Reversível.

from django.db import migrations, models

# antigo (última concluída) → novo (preencher agora)
_FORWARD = {
    "profile": "address",
    "address": "rg",
    "documents": "education",
    "education": "selfie",
}
_BACKWARD = {
    v: k for k, v in _FORWARD.items()
}  # selfie volta pra education (aprox. fiel)


def _remap(apps, mapping):
    # UPDATE único com Case/When: updates encadeados re-mapeariam em cascata
    # (profile→address e depois address→rg pegaria a linha recém-trocada).
    from django.db.models import Case, F, Value, When

    Enrollment = apps.get_model("users", "Enrollment")
    Enrollment.objects.filter(status__in=mapping).update(
        status=Case(
            *(When(status=old, then=Value(new)) for old, new in mapping.items()),
            default=F("status"),
        )
    )


def forward(apps, schema_editor):
    _remap(apps, _FORWARD)


def backward(apps, schema_editor):
    _remap(apps, _BACKWARD)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_remove_otpcode_notification_external_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "iniciada (preencher perfil)"),
                    ("address", "endereço"),
                    ("rg", "RG (dados + fotos)"),
                    ("education", "dados escolares"),
                    ("selfie", "selfie"),
                    ("awaiting_release", "aguardando liberação"),
                    ("completed", "concluída"),
                ],
                db_index=True,
                default="started",
                max_length=20,
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
