# Generated by Django 5.2.14 on 2026-06-11 17:37
# + RunPython editado à mão (plan/13): ordem nova do wizard começa no DOCUMENTO — matrículas
#   em `started` (etapa perfil, que morreu) ou `address` (que agora vem DEPOIS do rg) voltam
#   pra `rg`. Dados parciais (perfil/endereço) ficam intactos; o chain-skip pula o que já está
#   completo quando o aluno avançar. Reverso: noop (não há como saber quem era `started`).

from django.db import migrations, models


def _old_statuses_to_rg(apps, schema_editor):
    Enrollment = apps.get_model("users", "Enrollment")
    Enrollment.objects.filter(status__in=["started", "address"]).update(status="rg")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_rg_full_photo_rg_validated_at_rg_validation_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="selfie_taken_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="selfie enviada em"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("rg", "RG (fotos + dados)"),
                    ("address", "endereço"),
                    ("education", "dados escolares"),
                    ("selfie", "selfie (assinatura da matrícula)"),
                    ("awaiting_release", "aguardando liberação"),
                    ("completed", "concluída"),
                ],
                db_index=True,
                default="rg",
                max_length=20,
            ),
        ),
        migrations.RunPython(_old_statuses_to_rg, migrations.RunPython.noop),
    ]
