# Generated by Django 5.2.14 on 2026-06-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_enrollment_selfie_taken_at_alter_enrollment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("rg", "RG (fotos + dados)"),
                    ("address", "endereço"),
                    ("education", "dados escolares"),
                    ("selfie", "selfie (assinatura da matrícula)"),
                    ("awaiting_release", "aguardando liberação"),
                    ("fee_paid", "1ª parcela da taxa paga"),
                    ("fee_scheduled", "2ª parcela da taxa agendada"),
                    ("completed", "concluída"),
                ],
                db_index=True,
                default="rg",
                max_length=20,
            ),
        ),
    ]
