# Generated by Django 5.2.14 on 2026-06-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_enrollment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnh",
            name="full_photo",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="foto inteira"
            ),
        ),
        migrations.AddField(
            model_name="cnh",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="validado em"
            ),
        ),
        migrations.AddField(
            model_name="cnh",
            name="validation_result",
            field=models.JSONField(
                blank=True, null=True, verbose_name="resultado da validação"
            ),
        ),
        migrations.AddField(
            model_name="cnh",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "aguardando IA"),
                    ("approved", "aprovado"),
                    ("rejected", "reprovado (refazer)"),
                    ("review", "em revisão (coordenador decide)"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="validação IA",
            ),
        ),
    ]
