# Generated by Django 5.2.14 on 2026-06-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_candidate_doc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="selfie_taken_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="doc_type",
            field=models.CharField(
                blank=True,
                choices=[("rg", "RG"), ("cnh", "CNH")],
                db_index=True,
                max_length=4,
                null=True,
            ),
        ),
    ]
