# Generated by Django 5.2.14 on 2026-06-16 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_candidate_selfie_taken_at_alter_candidate_doc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="blocking",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="material",
            name="content_blocks",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="material",
            name="ephemeral",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="kind",
            field=models.CharField(
                choices=[
                    ("fixed", "fixa (todo promotor novo recebe)"),
                    (
                        "transitory",
                        "transitória (só os promotores já existentes ao publicar)",
                    ),
                ],
                db_index=True,
                default="fixed",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "iniciado"),
                    ("profile", "perfil"),
                    ("address", "endereço"),
                    ("documents", "documentos"),
                    ("pix", "chave pix"),
                    ("selfie", "selfie"),
                    ("completed", "concluído (aguardando aprovação do coordenador)"),
                    ("approved", "aprovado (virou promotor)"),
                    ("rejected", "rejeitado pelo coordenador"),
                ],
                db_index=True,
                default="started",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="text_content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="MaterialAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pendente"), ("approved", "aprovada")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="users.material",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "atribuição de matéria",
                "verbose_name_plural": "atribuições de matéria",
                "db_table": "users_training_assignment",
            },
        ),
        migrations.DeleteModel(
            name="Trainee",
        ),
        migrations.AddConstraint(
            model_name="materialassignment",
            constraint=models.UniqueConstraint(
                fields=("user", "material"), name="uniq_material_per_user"
            ),
        ),
    ]
