# Generated by Django 5.2.14 on 2026-06-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0001_initial"),
        ("users", "0024_remove_educationaldata_last_year_studied_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                condition=models.Q(("platform_login__gt", "")),
                fields=("platform_login",),
                name="uniq_student_platform_login",
            ),
        ),
    ]
