# Generated by Django 5.2.14 on 2026-06-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_student_uniq_student_platform_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdiploma",
            name="diploma_file",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="studentdiploma",
            name="transcript_file",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
