# Generated by Django 5.2.14 on 2026-07-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_studentdiploma_diploma_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="audio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="AddressProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="foto"
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_proof",
                        to="users.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "comprovante de residência",
                "verbose_name_plural": "comprovantes de residência",
                "db_table": "users_document_address_proof",
            },
        ),
    ]
