# Generated by Django 5.2.14 on 2026-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_candidate_consent_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressproof",
            name="kinship_provided_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="parentesco informado em"
            ),
        ),
        migrations.AddField(
            model_name="addressproof",
            name="kinship_relation",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="grau de parentesco do titular",
            ),
        ),
        migrations.AddField(
            model_name="addressproof",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="validado em"
            ),
        ),
        migrations.AddField(
            model_name="addressproof",
            name="validation_result",
            field=models.JSONField(
                blank=True, null=True, verbose_name="resultado da IA"
            ),
        ),
        migrations.AddField(
            model_name="addressproof",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "aguardando IA"),
                    ("approved", "aprovado"),
                    ("rejected", "reprovado (refazer)"),
                    ("review", "em revisão (coordenador decide)"),
                    ("needs_kinship", "aguardando explicação de parentesco"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="selfie_reject_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="bolsista",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="selfie_reject_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="education_completed",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="concluiu o nível?"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fundamental", "Ensino Fundamental"),
                    ("medio", "Ensino Médio"),
                ],
                max_length=16,
                null=True,
                verbose_name="escolaridade",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="selfie_needs_meeting",
            field=models.BooleanField(
                default=False, verbose_name="selfie exige encontro presencial"
            ),
        ),
        migrations.AddField(
            model_name="promoter",
            name="pre_matriculado",
            field=models.BooleanField(
                default=False, verbose_name="pré-matriculado (bolsa)"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="bolsista",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "iniciado"),
                    ("profile", "perfil"),
                    ("address", "endereço"),
                    ("documents", "documentos"),
                    ("pix", "chave pix"),
                    ("education", "escolaridade"),
                    ("selfie", "selfie"),
                    ("completed", "concluído (aguardando aprovação do coordenador)"),
                    ("approved", "aprovado (virou promotor)"),
                    ("rejected", "rejeitado pelo coordenador"),
                ],
                db_index=True,
                default="started",
                max_length=12,
            ),
        ),
    ]
