# Generated by Django 5.2.14 on 2026-07-13 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_alter_checkout_provider_payment_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        max_length=64, verbose_name="tipo da fonte rejeitada"
                    ),
                ),
                (
                    "source_external_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="external_id da fonte",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                ("description", models.TextField(verbose_name="descrição")),
                (
                    "action_label",
                    models.CharField(max_length=100, verbose_name="rótulo da ação"),
                ),
                (
                    "action_route",
                    models.CharField(max_length=200, verbose_name="rota da ação"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resolvido em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "bloqueio de validação",
                "verbose_name_plural": "bloqueios de validação",
                "db_table": "users_validation_block",
                "indexes": [
                    models.Index(
                        fields=["user", "resolved_at"],
                        name="users_valid_user_id_2d9713_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=("user", "source_type"),
                        name="uniq_active_block_per_source",
                    )
                ],
            },
        ),
    ]
