# Generated by Django 5.2.16 on 2026-09-04 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_profile_whatsapp_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_raw', models.CharField(blank=True, max_length=64)),
                ('utm_source', models.CharField(blank=True, max_length=128)),
                ('utm_medium', models.CharField(blank=True, max_length=128)),
                ('utm_campaign', models.CharField(blank=True, max_length=128)),
                ('utm_term', models.CharField(blank=True, max_length=128)),
                ('utm_content', models.CharField(blank=True, max_length=128)),
                ('gclid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('fbclid', models.CharField(blank=True, max_length=255)),
                ('fbp', models.CharField(blank=True, max_length=64)),
                ('fbc', models.CharField(blank=True, max_length=255)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('landing_url', models.URLField(blank=True, max_length=500)),
                ('sent_google', models.DateTimeField(blank=True, null=True)),
                ('sent_meta', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='users.lead')),
            ],
            options={
                'verbose_name': 'atribuição do lead',
                'verbose_name_plural': 'atribuições dos leads',
                'db_table': 'users_lead_attribution',
            },
        ),
    ]
