# Generated by Django 6.0.2 on 2026-03-24 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevenLabsTTSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, help_text='Texto enviado para conversão', null=True)),
                ('voice_id', models.CharField(blank=True, max_length=200, null=True)),
                ('audio_path', models.CharField(blank=True, max_length=500, null=True)),
                ('request_data', models.JSONField(blank=True, help_text='Dados enviados na requisição', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Dados de resposta da API ElevenLabs', null=True)),
                ('response_text', models.TextField(blank=True, help_text='Texto da resposta ElevenLabs', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log ElevenLabs TTS',
                'verbose_name_plural': 'Logs ElevenLabs TTS',
                'ordering': ['-created_at'],
            },
        ),
    ]
