# Generated by Django 5.1.15 on 2026-08-13 20:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color_primary',
            field=models.CharField(blank=True, default='', help_text='Hex (#RRGGBB) usado nos templates de e-mail.', max_length=7),
        ),
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.FileField(blank=True, help_text='Logo da marca. Use PNG ou SVG.', null=True, upload_to=accounts.models.account_logo_path),
        ),
    ]
