"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
import sys
from pathlib import Path
from urllib.parse import parse_qsl, quote, unquote, urlsplit
from dotenv import load_dotenv
from django.urls import reverse_lazy
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_optional_bool(name):
    value = os.getenv(name)
    if value is None:
        return None
    normalized = value.strip().lower()
    if normalized == "":
        return None
    return normalized in {"1", "true", "yes", "on"}


def _env_optional_float(name):
    value = os.getenv(name)
    if value is None:
        return None
    normalized = value.strip()
    if normalized == "":
        return None
    return float(normalized)


def _env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def _env_first(names, default=""):
    for name in names:
        value = os.getenv(name)
        if value is not None and str(value).strip():
            return value
    return default


def _normalize_origin(value):
    value = str(value or "").strip()
    if not value:
        return ""
    parsed = urlsplit(value)
    if parsed.scheme and parsed.netloc:
        return f"{parsed.scheme}://{parsed.netloc}"
    return value.rstrip("/")


def _env_origin_list(name, default=""):
    return [_normalize_origin(item) for item in _env_list(name, default)]


def _database_url_engine(database_url):
    parsed = urlsplit(str(database_url or "").strip())
    scheme = parsed.scheme.lower()
    if scheme in {"postgres", "postgresql", "psql", "pgsql"}:
        return "postgresql"
    if scheme in {"sqlite", "sqlite3"}:
        return "sqlite"
    return ""


def _resolve_sqlite_name():
    database_url = str(os.getenv("DATABASE_URL", "")).strip()
    if _database_url_engine(database_url) == "sqlite":
        parsed = urlsplit(database_url)
        sqlite_path = unquote(parsed.path or "").strip()
        if not sqlite_path or sqlite_path == "/":
            return str(BASE_DIR / "db.sqlite3")
        if sqlite_path.startswith("//"):
            return sqlite_path[1:]
        if sqlite_path.startswith("/"):
            sqlite_path = sqlite_path[1:]
        if os.path.isabs(sqlite_path):
            return sqlite_path
        return str(BASE_DIR / sqlite_path)

    configured_name = str(os.getenv("SQLITE_NAME", "")).strip()
    if not configured_name:
        return str(BASE_DIR / "db.sqlite3")
    if configured_name == ":memory:" or os.path.isabs(configured_name):
        return configured_name
    return str(BASE_DIR / configured_name)


def _build_sqlite_database_config():
    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": _resolve_sqlite_name(),
        "OPTIONS": {
            "timeout": SQLITE_TIMEOUT_SECONDS,
        },
    }


def _build_postgres_test_settings():
    config = {}

    test_name = str(
        _env_first(
            ["TEST_DATABASE_NAME", "TEST_POSTGRES_DB", "POSTGRES_TEST_DB"],
            "",
        )
    ).strip()
    test_charset = str(os.getenv("TEST_DATABASE_CHARSET", "UTF8")).strip()
    test_template = str(os.getenv("TEST_DATABASE_TEMPLATE", "template0")).strip()

    if test_name:
        config["NAME"] = test_name
    if test_charset:
        config["CHARSET"] = test_charset
    if test_template:
        config["TEMPLATE"] = test_template

    return config


def _build_postgres_database_config():
    database_url = str(os.getenv("DATABASE_URL", "")).strip()
    conn_max_age = int(os.getenv("DATABASE_CONN_MAX_AGE", 60))

    if database_url:
        parsed = urlsplit(database_url)
        options = dict(parse_qsl(parsed.query, keep_blank_values=True))
        config = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed.path.lstrip("/")),
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or ""),
            "CONN_MAX_AGE": conn_max_age,
        }
        if options:
            config["OPTIONS"] = options
        test_config = _build_postgres_test_settings()
        if test_config:
            config["TEST"] = test_config
        return config

    sslmode = str(_env_first(["POSTGRES_SSLMODE", "DB_SSLMODE"], "")).strip()
    config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": str(_env_first(["POSTGRES_DB", "POSTGRES_NAME", "DB_NAME"], "")).strip(),
        "USER": str(_env_first(["POSTGRES_USER", "DB_USER"], "")).strip(),
        "PASSWORD": str(_env_first(["POSTGRES_PASSWORD", "DB_PASSWORD"], "")).strip(),
        "HOST": str(_env_first(["POSTGRES_HOST", "DB_HOST"], "localhost")).strip(),
        "PORT": str(_env_first(["POSTGRES_PORT", "DB_PORT"], "5432")).strip(),
        "CONN_MAX_AGE": conn_max_age,
    }
    if sslmode:
        config["OPTIONS"] = {"sslmode": sslmode}
    test_config = _build_postgres_test_settings()
    if test_config:
        config["TEST"] = test_config
    return config


def _should_use_postgres_database():
    configured_engine = str(os.getenv("DATABASE_ENGINE", "")).strip().lower()
    if configured_engine in {"postgres", "postgresql", "psql", "pgsql"}:
        return True
    return _database_url_engine(os.getenv("DATABASE_URL", "")) == "postgresql"


def _build_postgres_url(*, async_driver=""):
    name = str(_env_first(["POSTGRES_DB", "POSTGRES_NAME", "DB_NAME"], "")).strip()
    if not name:
        return ""

    user = str(_env_first(["POSTGRES_USER", "DB_USER"], "")).strip()
    password = str(_env_first(["POSTGRES_PASSWORD", "DB_PASSWORD"], "")).strip()
    host = str(_env_first(["POSTGRES_HOST", "DB_HOST"], "localhost")).strip()
    port = str(_env_first(["POSTGRES_PORT", "DB_PORT"], "5432")).strip()
    sslmode = str(_env_first(["POSTGRES_SSLMODE", "DB_SSLMODE"], "")).strip()

    scheme = "postgresql"
    if async_driver:
        scheme = f"{scheme}+{async_driver}"

    auth = ""
    if user:
        auth = quote(user, safe="")
        if password:
            auth += f":{quote(password, safe='')}"
        auth += "@"

    url = f"{scheme}://{auth}{host}:{port}/{quote(name, safe='')}"
    if sslmode:
        url = f"{url}?sslmode={quote(sslmode, safe='')}"
    return url


def _build_testing_database_config():
    test_database_url = str(os.getenv("TEST_DATABASE_URL", "")).strip()
    test_engine = str(os.getenv("TEST_DATABASE_ENGINE", "")).strip().lower()

    if test_database_url and _database_url_engine(test_database_url) == "postgresql":
        original_database_url = os.getenv("DATABASE_URL")
        try:
            os.environ["DATABASE_URL"] = test_database_url
            return _build_postgres_database_config()
        finally:
            if original_database_url is None:
                os.environ.pop("DATABASE_URL", None)
            else:
                os.environ["DATABASE_URL"] = original_database_url

    if test_engine in {"postgres", "postgresql", "psql", "pgsql"}:
        original_engine = os.getenv("DATABASE_ENGINE")
        try:
            os.environ["DATABASE_ENGINE"] = "postgresql"
            return _build_postgres_database_config()
        finally:
            if original_engine is None:
                os.environ.pop("DATABASE_ENGINE", None)
            else:
                os.environ["DATABASE_ENGINE"] = original_engine

    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    }


def _default_taskiq_dashboard_storage():
    configured = str(os.getenv("TASKIQ_DASHBOARD_STORAGE", "")).strip().lower()
    if configured:
        return configured

    default_engine = DATABASES["default"]["ENGINE"]
    if default_engine == "django.db.backends.postgresql":
        return "postgres"
    return "sqlite"


def _default_taskiq_dashboard_database_dsn(*, storage_type):
    explicit_dsn = str(os.getenv("TASKIQ_DASHBOARD_DATABASE_DSN", "")).strip()
    if explicit_dsn:
        return explicit_dsn

    if storage_type == "postgres":
        postgres_dsn = str(os.getenv("TASKIQ_DASHBOARD_POSTGRES__DSN", "")).strip()
        if postgres_dsn:
            return postgres_dsn

        database_url = str(os.getenv("DATABASE_URL", "")).strip()
        if _database_url_engine(database_url) == "postgresql":
            parsed = urlsplit(database_url)
            return database_url.replace(f"{parsed.scheme}://", "postgresql+asyncpg://", 1)

        return _build_postgres_url(async_driver="asyncpg")

    sqlite_dsn = str(os.getenv("TASKIQ_DASHBOARD_SQLITE__DSN", "")).strip()
    if sqlite_dsn:
        return sqlite_dsn

    sqlite_file_path = str(os.getenv("TASKIQ_DASHBOARD_SQLITE__FILE_PATH", "")).strip()
    if sqlite_file_path:
        return f"sqlite+aiosqlite:///{sqlite_file_path}"

    sqlite_name = str(DATABASES["default"]["NAME"])
    if sqlite_name == ":memory:":
        return "sqlite+aiosqlite:///:memory:"
    return f"sqlite+aiosqlite:///{sqlite_name}"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-xf_1e&%*y6e8&1sn!+7%hqeug9%bpa3iewbp02wrfw1!vzp=mw",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", True)

ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")
for _host in ["localhost", "127.0.0.1", "0.0.0.0"]:
    if _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)


# Application definition
INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    


    # Custom Apps & Services
    'apps.authentication',
    'notifications',
    'apps.profiles',
    'apps.visitors',
    'apps.roles',
    'apps.captive',
    'apps.ministries',
    'apps.reception',
    'apps.worship',
    'apps.volunteer',
    'apps.lms',
    'apps.baptism',
    # M3.2 — credenciais (carteirinha digital QR com checagem online e
    # revogação remota pelo dirigente).
    'apps.credentials',
    # M3.4 — Apresentacao de criancas (solicitacao dos pais -> aprovacao
    # do pastor -> agendamento -> realizacao -> certificado OB3 paralelo).
    'apps.children_presentation',
    # Cargos ministeriais (cooperador/diácono/presbítero/evangelista/pastor).
    # PDD §3.1: NÃO são roles — são dados de domínio com histórico, aprovados
    # por pastor ativo. Coexiste com as 3 roles (visitante/congregado/membro).
    'apps.presbytery',
    # M3.1 — financeiro (contribuições + contas a pagar + relatórios).
    'apps.finance',
    # Dashboard — agregador de KPIs pastorais (GET /dashboard/summary).
    'apps.dashboard',
    # M2.3 — frente de servico (parent sem models) + sub-app midia.
    # Midia e redes sociais (geracao IA + cron de postagem). Demais
    # sub-departamentos (transmissao, multimidia, foto/registro) entram depois.
    'apps.servico',
    'apps.servico.midia',
    # Sub-apps de IA: só registrados se o SDK estiver instalado. Em
    # ambientes sem o pacote de TTS/vision o ``manage.py test`` não deve
    # quebrar — o módulo de domínio continua funcional via fallback
    # MiniMax. O provider ativo é resolvido por env (M1.7).
    'services.ai.minimax',
    # Migrado de services.communication.evolution no M1.6. label='evolution'
    # preservado para manter a tabela ``evolution_api_log`` e o historico de
    # migrations ja aplicadas em prod.
    'integrations.communication.evolution',
    # M1.7 — engine multi-provider (LLM + mídia). TTS primário ElevenLabs,
    # fallback MiniMax. Tabela ``ai_call`` grava 1 linha por tentativa.
    'integrations.ai',
    # M1.8 — tools de apoio (CPFHub + ViaCEP). Sem model (stateless).
    # Ordem alfabética segue o path: cpf antes de cep.
    'integrations.tools.cpf',
    'integrations.tools.cep',
    # M3.1 — integrações bancárias (parent + Asaas + InfinitePay).
    'integrations.bank',
    'integrations.bank.asaas',
    'integrations.bank.infinitepay',
]

# Filtra apps de IA cujo SDK de terceiros não está instalado (elevenlabs
# SDK + google-genai). Em ambientes de dev/test onde esses pacotes
# opcionais não estão presentes, ``manage.py test`` não pode quebrar —
# o módulo de domínio continua funcional via fallback MiniMax.
_INSTALLED_APPS = list(INSTALLED_APPS)
for _ai_app, _sdk_check in (
    ("services.ai.gemini", "google.genai"),
    ("services.ai.elevenlabs", "elevenlabs"),
):
    try:
        __import__(_sdk_check)
    except Exception:
        # SDK ausente — pula o app.
        continue
    _INSTALLED_APPS.append(_ai_app)
INSTALLED_APPS = _INSTALLED_APPS
del _ai_app, _sdk_check, _INSTALLED_APPS

# Espelhos parciais do repo (ex: sessões remotas de agente) podem não ter
# todos os apps locais commitados. Mesmo critério do filtro de SDKs acima:
# app local ausente é pulado com warning em vez de derrubar o boot. No
# checkout completo este filtro é no-op.
import importlib.util as _importlib_util

_INSTALLED_APPS = []
_missing_apps = []
for _app in INSTALLED_APPS:
    try:
        _spec = _importlib_util.find_spec(_app)
    except (ImportError, ModuleNotFoundError):
        _spec = None
    (_INSTALLED_APPS if _spec else _missing_apps).append(_app)
if _missing_apps:
    import warnings as _warnings

    _warnings.warn(
        "Apps ausentes neste checkout foram ignorados: " + ", ".join(_missing_apps),
        stacklevel=1,
    )
# Fallback do label ``evolution``: o app foi migrado pra
# ``integrations.communication.evolution`` no M1.6, mas espelhos que ainda
# não têm o novo caminho carregam o legado ``services.communication.evolution``
# (mesmo label e mesma tabela ``evolution_api_log``). No checkout completo o
# novo caminho existe e este bloco é no-op.
if "integrations.communication.evolution" in _missing_apps:
    try:
        if _importlib_util.find_spec("services.communication.evolution"):
            _INSTALLED_APPS.append("services.communication.evolution")
    except (ImportError, ModuleNotFoundError):
        pass
INSTALLED_APPS = _INSTALLED_APPS
del _importlib_util, _INSTALLED_APPS, _missing_apps, _app

# AI Keys Map
# Provider padrao de visao desde 2026-06-23: MiniMax.
MINIMAX_VISION_TIMEOUT = int(os.getenv("MINIMAX_VISION_TIMEOUT", 60))

# ----------------------------------------------------------------------------
# Open Badges 3.0 (credenciais) — desde 2026-06-23.
# Sliding window: cada acesso renova o token. Issuer canonico.
# ----------------------------------------------------------------------------
BADGE_ISSUER_NAME = os.getenv("BADGE_ISSUER_NAME", "IEADPG - Jardim Amália")
BADGE_SLIDING_WINDOW_HOURS = int(os.getenv("BADGE_SLIDING_WINDOW_HOURS", 24))
BADGE_ISSUER_URL = os.getenv(
    "BADGE_ISSUER_URL", "https://ieadpg.org.br/profile/issuer"
)

# ----------------------------------------------------------------------------
# LGPD — DESLIGADO por padrao desde 2026-06-23 (decisao do dono).
#
# O IEADPG NAO e fintech: compliance pesado custa tempo e complica UX sem
# retorno claro nessa fase. A flag abaixo DEVE ficar em ``False`` ate o
# dono autorizar explicitamente a ligacao. Ver memory:
# feedback-lgpd-off-by-default.
#
# Ja existe no sistema UM registro minimo de consentimento implicito no
# captive (apps.captive.models.CaptiveConsent) — apenas loga o ato de
# conectar + telefone + IP. NAO confundir com sistema LGPD completo:
# sem dialogo de consentimento, sem retencao automatica, sem
# export/delete APIs, sem base legal formal. E so um registro.
#
# Antes de adicionar qualquer feature de LGPD (consent_*, legal_basis_*,
# retention_*, /api/lgpd/*, dialog de consentimento), PERGUNTAR AO DONO
# e mudar esta flag para ``True``.
# ----------------------------------------------------------------------------
LGPD_ENABLED = _env_bool("LGPD_ENABLED", False)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_API_BASE_URL = os.getenv("GEMINI_API_BASE_URL", "https://generativelanguage.googleapis.com/v1beta")
GEMINI_REQUEST_TIMEOUT = int(os.getenv("GEMINI_REQUEST_TIMEOUT", 45))
GEMINI_IMAGE_MODELS = tuple(
    item.strip()
    for item in os.getenv(
        "GEMINI_IMAGE_MODELS",
        "gemini-3.1-flash-image-preview,gemini-2.5-flash-image,gemini-3-pro-image-preview",
    ).split(",")
    if item.strip()
)

ELEVENLABS_API_KEY = os.getenv("ELEVENLABS_API_KEY")
ELEVENLABS_REQUEST_TIMEOUT = int(os.getenv("ELEVENLABS_REQUEST_TIMEOUT", 30))
ELEVENLABS_VOICE_ID = os.getenv("ELEVENLABS_VOICE_ID", "JBFqnCBsd6RMkjVDRZzb")
ELEVENLABS_MODEL_ID = os.getenv("ELEVENLABS_MODEL_ID", "eleven_v3")
ELEVENLABS_LANGUAGE_CODE = os.getenv("ELEVENLABS_LANGUAGE_CODE", "").strip() or None
ELEVENLABS_OUTPUT_FORMAT = os.getenv("ELEVENLABS_OUTPUT_FORMAT", "mp3_44100_128")
ELEVENLABS_CONTEXT_PROFILE = os.getenv("ELEVENLABS_CONTEXT_PROFILE", "").strip()
ELEVENLABS_V3_PREFIX_TAGS = os.getenv("ELEVENLABS_V3_PREFIX_TAGS", "").strip()
ELEVENLABS_VOICE_STABILITY = _env_optional_float("ELEVENLABS_VOICE_STABILITY")
ELEVENLABS_VOICE_SIMILARITY_BOOST = _env_optional_float("ELEVENLABS_VOICE_SIMILARITY_BOOST")
ELEVENLABS_VOICE_STYLE = _env_optional_float("ELEVENLABS_VOICE_STYLE")
ELEVENLABS_VOICE_SPEED = _env_optional_float("ELEVENLABS_VOICE_SPEED")
ELEVENLABS_VOICE_USE_SPEAKER_BOOST = _env_optional_bool("ELEVENLABS_VOICE_USE_SPEAKER_BOOST")

# M1.7 — IA multi-provider (integrations.ai).
# FONTE UNICA: 1 chain por capability (TEXT/VISION/IMAGE/TTS) em CSV
# ``provider:model,provider:model,...`` — 1º é o primário; falha retryable
# cai pro próximo. App só chama ``integrations.ai.{text,vision,image,tts}``
# (mesma assinatura para todas). Pra trocar provedor é mudar o .env, nunca
# o código. ``IA_FALLBACK_CHAIN`` é alias retrocompativel de IA_TEXT_CHAIN.
#
# Decisão 2026-06-24 (ver memória feedback-ai-minimax-vision):
# - Texto: DeepSeek primario, MiniMax fallback (Groq descartado — custo)
# - Visao: MiniMax primario, Gemini fallback
# - Imagem: MiniMax primario, Gemini fallback
# - TTS:   ElevenLabs primario, MiniMax fallback
# Exemplo de .env:
#   IA_TEXT_CHAIN=deepseek:deepseek-chat,minimax:MiniMax-Text-01
#   IA_VISION_CHAIN=minimax:MiniMax-M3,gemini:gemini-2.5-flash
#   IA_IMAGE_CHAIN=minimax:image-01,gemini:gemini-2.5-flash-image
#   IA_TTS_CHAIN=elevenlabs:eleven_v3,minimax:speech-2.8-hd
IA_TEXT_CHAIN = os.getenv("IA_TEXT_CHAIN", "")
IA_VISION_CHAIN = os.getenv("IA_VISION_CHAIN", "")
IA_IMAGE_CHAIN = os.getenv("IA_IMAGE_CHAIN", "")
IA_TTS_CHAIN = os.getenv("IA_TTS_CHAIN", "")
# Alias retrocompativel — code legado lê IA_FALLBACK_CHAIN (default = IA_TEXT_CHAIN).
IA_FALLBACK_CHAIN = os.getenv("IA_FALLBACK_CHAIN", "") or os.getenv("IA_TEXT_CHAIN", "")
# OmniRouter — provider único do cérebro de texto desde 2026-07-19 (gateway
# OpenAI-compatible na VPN). Ver ``integrations/ai/providers._KNOWN_PROVIDERS``.
IA_ENABLED_OMNIROUTER = _env_bool("IA_ENABLED_OMNIROUTER", False)
IA_OMNIROUTER_BASE_URL = os.getenv("IA_OMNIROUTER_BASE_URL", "")
IA_OMNIROUTER_API_KEY = os.getenv("IA_OMNIROUTER_API_KEY", "")
IA_ENABLED_GROQ = _env_bool("IA_ENABLED_GROQ", False)
IA_GROQ_BASE_URL = os.getenv("IA_GROQ_BASE_URL", "")
IA_GROQ_API_KEY = os.getenv("IA_GROQ_API_KEY", "")
IA_ENABLED_DEEPSEEK = _env_bool("IA_ENABLED_DEEPSEEK", False)
IA_DEEPSEEK_BASE_URL = os.getenv("IA_DEEPSEEK_BASE_URL", "")
IA_DEEPSEEK_API_KEY = os.getenv("IA_DEEPSEEK_API_KEY", "")
IA_ENABLED_MINIMAX = _env_bool("IA_ENABLED_MINIMAX", False)
IA_MINIMAX_BASE_URL = os.getenv("IA_MINIMAX_BASE_URL", "https://api.minimax.chat/v1")
IA_MINIMAX_API_KEY = os.getenv("IA_MINIMAX_API_KEY", "")
IA_ENABLED_OPENAI = _env_bool("IA_ENABLED_OPENAI", False)
IA_OPENAI_BASE_URL = os.getenv("IA_OPENAI_BASE_URL", "https://api.openai.com/v1")
IA_OPENAI_API_KEY = os.getenv("IA_OPENAI_API_KEY", "")

# M1.13 — MiniMax (TTS secundário / fallback do ElevenLabs).
# Sem clone do dirigente agora (sem LGPD de biometria vocal). Voz masculina
# fixa vem do ELEVENLABS_VOICE_ID — MiniMax é só fallback se ElevenLabs cair.
#
# ALIASES LEGADOS: ``MINIMAX_*`` (M1.7 namespace) continua aceito pra
# retrocompat — cai pra ``IA_MINIMAX_*`` se vazio. Single source of truth =
# ``IA_MINIMAX_*`` (registry). M5 remove os aliases em M5.1 (próxima).
MINIMAX_API_KEY = os.getenv("MINIMAX_API_KEY", "") or os.getenv("IA_MINIMAX_API_KEY", "")
MINIMAX_BASE_URL = (
    os.getenv("MINIMAX_BASE_URL", "") or os.getenv("IA_MINIMAX_BASE_URL", "https://api.minimax.chat/v1")
)
MINIMAX_TTS_MODEL = os.getenv("MINIMAX_TTS_MODEL", "speech-2.8-hd")
MINIMAX_VOICE_MALE = os.getenv("MINIMAX_VOICE_MALE", "")
MINIMAX_VOICE_FEMALE = os.getenv("MINIMAX_VOICE_FEMALE", "")
MINIMAX_VISION_MODEL = os.getenv("MINIMAX_VISION_MODEL", "MiniMax-M3")

EVOLUTION_API_URL = os.getenv("EVOLUTION_API_URL", "")
EVOLUTION_INSTANCE = os.getenv("EVOLUTION_INSTANCE", "default")
EVOLUTION_API_KEY = os.getenv("EVOLUTION_API_KEY", "")
EVOLUTION_REQUEST_TIMEOUT = int(os.getenv("EVOLUTION_REQUEST_TIMEOUT", 30))
# TTL do cache em memoria para resolucao da variante BR (nono digito) na Evolution.
# Usado por ``integrations.communication.evolution.EvolutionRequestClient.resolve_br_number``.
EVOLUTION_BR_JID_CACHE_TTL_S = int(os.getenv("EVOLUTION_BR_JID_CACHE_TTL_S", "3600"))

# M1.8 — tool de CPF (CPFHub.io). Api-key é obrigatória pro lookup funcionar;
# o system check ``cpf.W001`` (Warning) avisa se faltar. Retry em 429/5xx
# (3 retries, backoff 1s/2s/4s) é feito em ``integrations.tools.cpf.scripts.cpfhub``.
CPFHUB_API_URL = os.getenv("CPFHUB_API_URL", "https://api.cpfhub.io/cpf")
CPFHUB_API_KEY = os.getenv("CPFHUB_API_KEY", "")
CPFHUB_REQUEST_TIMEOUT = int(os.getenv("CPFHUB_REQUEST_TIMEOUT", 10))

# M1.8 — tool de CEP (ViaCEP). API pública, sem api-key, sem setting
# dedicada (URL/timeout são constantes em ``integrations.tools.cep.scripts.viacep``).

# ----------------------------------------------------------------------------
# Captive Portal Wi-Fi (apps.captive) — design "Fluxo Captive Portal IEADPG".
# O agente local (na rede da igreja, junto do controlador Wi-Fi) chama
# ``POST /portal/session/start`` com o MAC do dispositivo; MAC desconhecido é
# redirecionado pro portal (HTMX). Depois do OTP o backend devolve a liberação
# ao agente local — push HTTP assinado (HMAC) ou polling — com uma credencial
# assinada que identifica o MAC autorizado.
# ----------------------------------------------------------------------------
# Chave que o agente local manda no header ``X-Agent-Key`` (auth agente->cloud).
CAPTIVE_AGENT_KEY = os.getenv("CAPTIVE_AGENT_KEY", "")
# Segredo compartilhado que assina credenciais de grant e o push cloud->agente.
CAPTIVE_AGENT_SECRET = os.getenv("CAPTIVE_AGENT_SECRET", "")
# URL do agente local pra push de liberação (ex: http://10.1.20.50:8899/grant).
# Vazio = só polling (``GET /portal/agent/grants``).
CAPTIVE_LOCAL_CALLBACK_URL = os.getenv("CAPTIVE_LOCAL_CALLBACK_URL", "")
CAPTIVE_CALLBACK_TIMEOUT = int(os.getenv("CAPTIVE_CALLBACK_TIMEOUT", 4))
CAPTIVE_CALLBACK_RETRIES = int(os.getenv("CAPTIVE_CALLBACK_RETRIES", 3))
# Validade da liberação de internet por MAC.
CAPTIVE_GRANT_TTL_SECONDS = int(os.getenv("CAPTIVE_GRANT_TTL_SECONDS", 12 * 3600))
# E1 — 3 falhas de OTP bloqueiam por 10 min.
CAPTIVE_OTP_MAX_ATTEMPTS = int(os.getenv("CAPTIVE_OTP_MAX_ATTEMPTS", 3))
CAPTIVE_OTP_LOCK_MINUTES = int(os.getenv("CAPTIVE_OTP_LOCK_MINUTES", 10))
# Base pública do portal usada na URL de redirect devolvida ao agente.
CAPTIVE_PORTAL_BASE_URL = os.getenv("CAPTIVE_PORTAL_BASE_URL", "")
# Link do app mostrado na tela final (S7).
CAPTIVE_APP_URL = os.getenv("CAPTIVE_APP_URL", "https://app.ieadpg.org")
# Agenda de cultos fallback (Fase D) quando apps.worship não tem os models
# neste checkout: "dia hh:mm-hh:mm" separados por ";" (dias: mon..sun ou
# seg/ter/qua/qui/sex/sab/dom).
CAPTIVE_WORSHIP_SCHEDULE = os.getenv(
    "CAPTIVE_WORSHIP_SCHEDULE", "dom 09:00-11:30;dom 18:30-21:30;qua 19:30-21:30"
)
CAPTIVE_WORSHIP_TOLERANCE_MIN = int(os.getenv("CAPTIVE_WORSHIP_TOLERANCE_MIN", 30))
# Passo 21 — job de boas-vindas pós-culto (TTS) N min após o fim do culto.
CAPTIVE_POST_WORSHIP_DELAY_MIN = int(os.getenv("CAPTIVE_POST_WORSHIP_DELAY_MIN", 15))

# M3.1 — Asaas (PIX/boleto, webhook).
# Api-key obrigatória (system check ``bank_asaas.E001`` trava boot sem ela).
# Em dev, configure ``ASAAS_API_KEY=sk-dev-dummy`` pra ativar o modo mock
# (client detecta o prefixo ``sk-dev-*`` e devolve payload FAKE sem chamar API).
# Webhook secret é separado — autentica só os endpoints públicos que o Asaas
# chama de volta (header ``asaas-access-token``).
ASAAS_API_KEY = os.getenv("ASAAS_API_KEY", "")
# ``ASAAS_WEBHOOK_TOKEN`` é o nome pedido pelo task M3.2; mantemos o alias
# ``ASAAS_WEBHOOK_SECRET`` (já usado pelo ``integrations.bank.asaas.security``)
# pra retrocompatibilidade — ambos apontam pro mesmo env var.
ASAAS_WEBHOOK_TOKEN = os.getenv("ASAAS_WEBHOOK_TOKEN", "") or os.getenv(
    "ASAAS_WEBHOOK_SECRET", ""
)
ASAAS_WEBHOOK_SECRET = ASAAS_WEBHOOK_TOKEN
ASAAS_BASE_URL = os.getenv("ASAAS_BASE_URL", "https://api.asaas.com/v3")
ASAAS_REQUEST_TIMEOUT = int(os.getenv("ASAAS_REQUEST_TIMEOUT", 10))

# M3.1 — InfinitePay (cartão).
# Autentica só pelo ``handle`` (InfiniteTag) — não existe api-key.
# System check ``bank_infinitepay.E001`` trava boot sem handle. Em dev, use
# ``INFINITEPAY_HANDLE=dev`` pra ativar o modo mock.
INFINITEPAY_HANDLE = os.getenv("INFINITEPAY_HANDLE", "")
INFINITEPAY_BASE_URL = os.getenv("INFINITEPAY_BASE_URL", "https://api.infinitepay.io")
INFINITEPAY_HTTP_TIMEOUT = int(os.getenv("INFINITEPAY_HTTP_TIMEOUT", 10))

EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 25))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", False)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", False)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "webmaster@localhost")
URL_FROTEND = os.getenv("URL_FROTEND", os.getenv("URL_FRONTEND", "https://app.ieadpg.org"))
AUTH_LOGIN_OTP_TTL_SECONDS = int(os.getenv("AUTH_LOGIN_OTP_TTL_SECONDS", 600))
AUTH_LOGIN_OTP_COOLDOWN_SECONDS = int(os.getenv("AUTH_LOGIN_OTP_COOLDOWN_SECONDS", 60))
AUTH_LOGIN_OTP_MAX_SENDS_PER_WINDOW = int(os.getenv("AUTH_LOGIN_OTP_MAX_SENDS_PER_WINDOW", 5))
AUTH_LOGIN_OTP_WINDOW_SECONDS = int(os.getenv("AUTH_LOGIN_OTP_WINDOW_SECONDS", 900))

# Roles — catálogo de transições (lido por apps/roles/catalog.py no boot).
ROLE_RULES = json.loads(
    os.getenv(
        "ROLE_RULES",
        '[{"from_role": null, "to_role": "visitante", "mode": "add"}, '
        '{"from_role": "visitante", "to_role": "congregado", "mode": "replace"}, '
        '{"from_role": "congregado", "to_role": "membro", "mode": "replace"}]',
    )
)
SQLITE_TIMEOUT_SECONDS = float(os.getenv("SQLITE_TIMEOUT_SECONDS", 20))
TESTING = "pytest" in sys.modules or any(arg in {"test", "pytest"} for arg in sys.argv[1:])

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": (
        _build_testing_database_config()
        if TESTING and not _env_bool("TEST_DATABASE_USE_PRIMARY", False)
        else (
            _build_postgres_database_config()
            if _should_use_postgres_database()
            else _build_sqlite_database_config()
        )
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
APP_BASE_URL = os.getenv("APP_BASE_URL", "http://localhost:8000")
CORS_ALLOW_ALL_ORIGINS = _env_bool("CORS_ALLOW_ALL_ORIGINS", True)
CORS_ALLOWED_ORIGINS = _env_origin_list(
    "CORS_ALLOWED_ORIGINS",
    ",".join(
        [
            "https://app.ieadpg.org",
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "https://api-ieadpg.m33.live",
        ]
    ),
)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.ok\.kimi\.link$",
]
CORS_ALLOW_CREDENTIALS = _env_bool("CORS_ALLOW_CREDENTIALS", True)
CSRF_TRUSTED_ORIGINS = _env_origin_list(
    "CSRF_TRUSTED_ORIGINS",
    ",".join(
        [
            "https://api-ieadpg.m33.live",
            "https://app.ieadpg.org",
            "https://*.ok.kimi.link",
            "http://localhost:3000",
            "http://127.0.0.1:3000",
        ]
    ),
)


# Taskiq Configuration
# https://github.com/taskiq-python/taskiq
TASKIQ_REDIS_URL = os.getenv("TASKIQ_REDIS_URL", "redis://localhost:6379/0")
TASKIQ_QUEUE_NAME = os.getenv("TASKIQ_QUEUE_NAME", "taskiq")
TASKIQ_BROKER_NAME = os.getenv("TASKIQ_BROKER_NAME", "ieadpg_worker")
TASKIQ_ENABLED = _env_bool("TASKIQ_ENABLED", not TESTING)
TASKIQ_EAGER = _env_bool("TASKIQ_EAGER", False)
TASKIQ_DASHBOARD_HOST = os.getenv("TASKIQ_DASHBOARD_HOST", "0.0.0.0")
TASKIQ_DASHBOARD_PORT = int(os.getenv("TASKIQ_DASHBOARD_PORT", "9000"))
TASKIQ_DASHBOARD_TOKEN = os.getenv("TASKIQ_DASHBOARD_TOKEN", "supersecret")
TASKIQ_DASHBOARD_ROOT_PATH = os.getenv("TASKIQ_DASHBOARD_ROOT_PATH", "").rstrip("/")
TASKIQ_DASHBOARD_STORAGE = _default_taskiq_dashboard_storage()
TASKIQ_DASHBOARD_DATABASE_DSN = _default_taskiq_dashboard_database_dsn(
    storage_type=TASKIQ_DASHBOARD_STORAGE,
)
TASKIQ_DASHBOARD_URL = os.getenv(
    "TASKIQ_DASHBOARD_URL",
    f"http://localhost:{TASKIQ_DASHBOARD_PORT}{TASKIQ_DASHBOARD_ROOT_PATH}",
).rstrip("/") + "/"

# Celery-compatible settings (for compatibility with existing code)
CELERY_BROKER_URL = TASKIQ_REDIS_URL
CELERY_RESULT_BACKEND = TASKIQ_REDIS_URL


# Unfold Configuration
# https://github.com/unfoldadmin/django-unfold

UNFOLD = {
    "SITE_TITLE": "IEADPG Admin",
    "SITE_HEADER": "IEADPG Admin",
    "SITE_SUBHEADER": "Sistema de Gestão",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("icon-light.svg"),
        "dark": lambda request: static("icon-dark.svg"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("logo-light.svg"),
        "dark": lambda request: static("logo-dark.svg"),
    },
    "SITE_SYMBOL": "speed",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("favicon.svg"),
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,
    # "ENVIRONMENT": "production",
    # "DASHBOARD_CALLBACK": "apps.authentication.views.dashboard_callback",
    "LOGIN": {
        "image": lambda request: static("sample/login-bg.jpg"),
        "redirect_after": lambda request: "/admin/",
    },
    "STYLES": [
        lambda request: static("css/styles.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/scripts.js"),
    ],
    "COLORS": {
        "primary": {
            "50": "#f0f9ff",
            "100": "#e0f2fe",
            "200": "#bae6fd",
            "300": "#7dd3fc",
            "400": "#38bdf8",
            "500": "#0ea5e9",
            "600": "#0284c7",
            "700": "#0369a1",
            "800": "#075985",
            "900": "#0c4a6e",
            "950": "#082f49",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇧🇪",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Menu Principal"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Usuários"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Perfis"),
                        "icon": "person",
                        "link": reverse_lazy("admin:profiles_profile_changelist"),
                    },
                ],
            },
            {
                "title": _("Visitantes"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Visitantes"),
                        "icon": "group",
                        "link": reverse_lazy("admin:visitors_visitor_changelist"),
                    },
                    {
                        "title": _("Logs de API"),
                        "icon": "monitoring",
                        "link": reverse_lazy("admin:visitors_visitorapilog_changelist"),
                    },
                ],
            },
            {
                "title": _("Notificações"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Notificações"),
                        "icon": "notifications",
                        "link": reverse_lazy("admin:notifications_notification_changelist"),
                    },
                    {
                        "title": _("Logs"),
                        "icon": "history",
                        "link": reverse_lazy("admin:notifications_notificationlog_changelist"),
                    },
                ],
            },
        ],
    },
    # "TABS": [
    #     {
    #         "models": [
    #             "auth.user",
    #         ],
    #         "items": [
    #             {
    #                 "title": _("Informações"),
    #                 "link": reverse_lazy("admin:auth_user_change", args=["__pk__"]),
    #             },
    #         ],
    #     },
    # ],
}
