# Generated by Django 6.0.2 on 2026-02-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_address_state_alter_address_zipcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Quando informado, sincroniza nome/sobrenome no usuario relacionado.', max_length=255, verbose_name='nome completo'),
        ),
    ]
