# Generated by Django 6.0.2 on 2026-03-24 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['state', 'city', 'street', 'number'], 'verbose_name': 'endereço', 'verbose_name_plural': 'endereços'},
        ),
        migrations.AlterModelOptions(
            name='addressproof',
            options={'ordering': ['-created_at'], 'verbose_name': 'comprovante de endereço', 'verbose_name_plural': 'comprovantes de endereço'},
        ),
        migrations.AlterModelOptions(
            name='schooltranscript',
            options={'verbose_name': 'histórico escolar', 'verbose_name_plural': 'históricos escolares'},
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Brasil', max_length=80, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=20, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], db_index=True, max_length=2, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='addressproof',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='cpf',
            name='number',
            field=models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, verbose_name='número do CPF'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(help_text='Formato: (00) 00000-0000', max_length=20, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='profiles.address', verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('incomplete_elementary', 'Fundamental incompleto'), ('complete_elementary', 'Fundamental completo'), ('incomplete_high_school', 'Médio incompleto'), ('complete_high_school', 'Médio completo'), ('incomplete_college', 'Superior incompleto'), ('complete_college', 'Superior completo'), ('postgraduate', 'Pós-graduação'), ('master', 'Mestrado'), ('doctorate', 'Doutorado'), ('not_informed', 'Não informado')], default='', max_length=30, verbose_name='nível de escolaridade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Quando informado, sincroniza nome e sobrenome no usuário relacionado.', max_length=255, verbose_name='nome completo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Feminino'), ('male', 'Masculino'), ('non_binary', 'Não binário'), ('other', 'Outro'), ('not_informed', 'Nao informado')], default='', max_length=20, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('widowed', 'Viúvo(a)'), ('stable_union', 'União estável'), ('not_informed', 'Não informado')], default='', max_length=20, verbose_name='estado civil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='nome da mãe'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
