# Generated by Django 6.0.3 on 2026-04-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Feminino'), ('male', 'Masculino')], default='', max_length=20, verbose_name='sexo/gênero'),
        ),
    ]
