# Generated by Django 5.2.14 on 2026-06-30 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai", "0003_alter_aicall_operation"),
        ("users", "0026_studentdiploma_diploma_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20, unique=True)),
                ("last_seen_at", models.DateTimeField()),
                ("hourly_count", models.PositiveIntegerField(default=0)),
                ("hourly_window_start", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                (
                    "audience",
                    models.CharField(db_index=True, default="unknown", max_length=20),
                ),
                (
                    "state",
                    models.CharField(db_index=True, default="open", max_length=20),
                ),
                ("last_activity", models.DateTimeField(auto_now=True, db_index=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_conversations",
                        to="users.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InboundEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "wa_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("event", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("source_ip", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["received_at"], name="bot_inbound_receive_13fac9_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direction", models.CharField(max_length=10)),
                ("text", models.TextField()),
                (
                    "wa_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "ai_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ai.aicall",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bot.conversation",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["phone", "state"], name="bot_convers_phone_0285f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="bot_message_convers_dedde6_idx",
            ),
        ),
    ]
