# Generated by Django 6.0.3 on 2026-04-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_visitor_christianity_type_visitor_religion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='date_of_visit',
            field=models.DateField(blank=True, null=True, verbose_name='data da visita'),
        ),
    ]
