# Generated by Django 6.0.3 on 2026-04-06 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_alter_visitor_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorApiLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(blank=True, help_text='Operacao executada no endpoint', max_length=120, null=True)),
                ('request_method', models.CharField(blank=True, help_text='Metodo HTTP da requisicao', max_length=10, null=True)),
                ('path', models.CharField(blank=True, help_text='Caminho da rota acessada', max_length=255, null=True)),
                ('authenticated_user_id', models.PositiveIntegerField(blank=True, help_text='Usuario autenticado vinculado ao request', null=True)),
                ('authenticated_profile_uuid', models.CharField(blank=True, help_text='Profile UUID autenticado no request', max_length=36, null=True)),
                ('success', models.BooleanField(default=False)),
                ('status_code', models.PositiveIntegerField(blank=True, help_text='Status HTTP retornado', null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Duracao do request em milissegundos', null=True)),
                ('request_data', models.JSONField(blank=True, help_text='Dados recebidos no endpoint', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Dados retornados pelo endpoint', null=True)),
                ('response_text', models.TextField(blank=True, help_text='Resumo textual da resposta', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Erro capturado na execucao', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'log da API de visitantes',
                'verbose_name_plural': 'logs da API de visitantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
