# Generated by Django 5.1.15 on 2026-08-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ai_api_key',
            field=models.CharField(blank=True, default='sk-d3786a77f7a483da-d7292e-5e7de527', max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='ai_url',
            field=models.CharField(blank=True, default='http://10.0.1.35/v1/chat/completions', max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='is_setup_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='setup_step',
            field=models.IntegerField(default=1),
        ),
    ]
