# Generated by Django 6.0.3 on 2026-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=20)),
                ('operation', models.CharField(choices=[('text', 'text'), ('json', 'json'), ('chat', 'chat'), ('summarize', 'summarize'), ('extract', 'extract'), ('grade', 'grade'), ('vision', 'vision'), ('image', 'image'), ('tts', 'tts'), ('ocr', 'ocr')], max_length=20)),
                ('model', models.CharField(max_length=60)),
                ('caller', models.CharField(db_index=True, max_length=60)),
                ('status', models.CharField(choices=[('success', 'success'), ('error', 'error')], max_length=10)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_hit_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_miss_tokens', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('latency_ms', models.IntegerField()),
                ('finish_reason', models.CharField(blank=True, default='', max_length=40)),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
                ('error_message', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_call',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='ai_call_created_2e439d_idx'), models.Index(fields=['operation', 'status'], name='ai_call_operati_9829f7_idx'), models.Index(fields=['provider', 'model', 'status'], name='ai_call_provide_678a90_idx')],
            },
        ),
    ]
