# Generated by Django 6.0.3 on 2026-04-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Somente telefone')], default=1, verbose_name='status'),
        ),
    ]
