# Generated by Django 6.0.3 on 2026-04-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_visitor_date_of_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'visitante', 'verbose_name_plural': 'visitantes'},
        ),
    ]
