# Generated by Django 6.0.3 on 2026-04-06 00:00

from django.db import migrations, models


def resequence_visitor_statuses(apps, schema_editor):
    Visitor = apps.get_model("visitors", "Visitor")

    Visitor.objects.filter(status=5).update(status=4)
    Visitor.objects.filter(status=15).update(status=14)


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0006_alter_visitor_options"),
    ]

    operations = [
        migrations.RunPython(resequence_visitor_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="visitor",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Cadastro online realizado"),
                    (2, "Dados iniciais salvos - online"),
                    (3, "Endereço salvo - online"),
                    (4, "Aguardando visita presencial"),
                    (11, "Visitante presencial registrado"),
                    (12, "Dados iniciais salvos - presencial"),
                    (13, "Endereço salvo - presencial"),
                    (14, "Aguardando coleta do presente de boas-vindas"),
                    (21, "Aguardando contato da equipe de recepção"),
                ],
                default=1,
                verbose_name="status",
            ),
        ),
    ]
