# Generated by Django 6.0.3 on 2026-04-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_resequence_visitor_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='religion',
            field=models.CharField(blank=True, choices=[('christianity', 'Cristianismo'), ('spiritism', 'Espiritismo'), ('african_origin', 'Religião de matriz Africana - Umbanda/Candomblé'), ('islam', 'Islamismo'), ('judaism', 'Judaísmo'), ('buddhism', 'Budismo'), ('no_religion', 'Sem religião'), ('other', 'Outra')], default='', max_length=40, verbose_name='religião'),
        ),
    ]
