# Generated by Django 6.0.3 on 2026-04-04 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_address_options_alter_addressproof_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpf',
            name='profile',
        ),
        migrations.RemoveConstraint(
            model_name='personaldocument',
            name='unique_personal_document_per_type',
        ),
        migrations.RemoveField(
            model_name='schoolcertificate',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='schooltranscript',
            name='profile',
        ),
        migrations.DeleteModel(
            name='CPF',
        ),
        migrations.RemoveField(
            model_name='personaldocument',
            name='profile',
        ),
        migrations.DeleteModel(
            name='SchoolCertificate',
        ),
        migrations.DeleteModel(
            name='SchoolTranscript',
        ),
        migrations.DeleteModel(
            name='PersonalDocument',
        ),
    ]
