# Generated by Django 5.2.14 on 2026-06-01 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("caller", models.CharField(max_length=100)),
                (
                    "recipient_phone",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("text", models.TextField()),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("mail_template", models.CharField(default="default", max_length=50)),
                ("media_url", models.CharField(blank=True, max_length=500, null=True)),
                ("media_type", models.CharField(blank=True, max_length=20, null=True)),
                ("gender", models.CharField(blank=True, max_length=1, null=True)),
                ("want_whatsapp", models.BooleanField(default=True)),
                ("want_email", models.BooleanField(default=False)),
                ("want_tts", models.BooleanField(default=False)),
                (
                    "whatsapp_status",
                    models.CharField(
                        choices=[
                            ("pending", "pendente"),
                            ("sent", "enviado"),
                            ("failed", "falhou"),
                            ("skipped", "ignorado"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("pending", "pendente"),
                            ("sent", "enviado"),
                            ("failed", "falhou"),
                            ("skipped", "ignorado"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "tts_status",
                    models.CharField(
                        choices=[
                            ("pending", "pendente"),
                            ("sent", "enviado"),
                            ("failed", "falhou"),
                            ("skipped", "ignorado"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("whatsapp_error", models.TextField(blank=True, null=True)),
                ("email_error", models.TextField(blank=True, null=True)),
                ("tts_error", models.TextField(blank=True, null=True)),
                (
                    "tts_audio_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
