# Generated by Django 5.2.14 on 2026-06-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="want_sanitize",
            field=models.BooleanField(default=False),
        ),
    ]
