# Generated by Django 5.2.14 on 2026-07-02 03:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0003_remove_notification_want_sanitize"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("event", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "body_md",
                    models.TextField(
                        help_text="Conteúdo em Markdown. Placeholders {nome}, {nome-completo}, {valor}..."
                    ),
                ),
                (
                    "is_tts",
                    models.BooleanField(
                        default=False, help_text="Tenta voice-note; falha -> texto."
                    ),
                ),
                (
                    "storytelling",
                    models.BooleanField(
                        default=False, help_text="IA gera o teor (body_md = fallback)."
                    ),
                ),
                (
                    "story_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Instrução p/ o LLM (só se storytelling=True).",
                        null=True,
                    ),
                ),
                (
                    "channels",
                    models.CharField(
                        default="whatsapp,email",
                        help_text="Canais separados por vírgula.",
                        max_length=40,
                    ),
                ),
                ("media_url", models.CharField(blank=True, max_length=500, null=True)),
                ("media_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "mail_template",
                    models.CharField(
                        default="default",
                        help_text="Slug do wrapper HTML do app mail.",
                        max_length=50,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "template de notificação",
                "verbose_name_plural": "templates de notificação",
            },
        ),
        migrations.CreateModel(
            name="Trigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "fires_on",
                    models.CharField(
                        help_text="Descrição humana do gatilho (ex.: 'Após pagamento confirmado').",
                        max_length=200,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="App/serviço emissor (ex.: 'users.roles.lead').",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("delay_minutes", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trigger",
                        to="notify.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "gatilho de notificação",
                "verbose_name_plural": "gatilhos de notificação",
            },
        ),
    ]
