# Generated by Django 5.2.14 on 2026-07-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0004_template_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="email_status",
            field=models.CharField(
                choices=[
                    ("pending", "pendente"),
                    ("sending", "enviando"),
                    ("sent", "enviado"),
                    ("failed", "falhou"),
                    ("skipped", "ignorado"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="tts_status",
            field=models.CharField(
                choices=[
                    ("pending", "pendente"),
                    ("sending", "enviando"),
                    ("sent", "enviado"),
                    ("failed", "falhou"),
                    ("skipped", "ignorado"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="whatsapp_status",
            field=models.CharField(
                choices=[
                    ("pending", "pendente"),
                    ("sending", "enviando"),
                    ("sent", "enviado"),
                    ("failed", "falhou"),
                    ("skipped", "ignorado"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
