# Generated by Django 5.2.16 on 2026-08-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_restore_template_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='story_prompt',
        ),
        migrations.RemoveField(
            model_name='template',
            name='storytelling',
        ),
    ]
