# Generated by Django 6.0.3 on 2026-07-28 14:52

import apps.captive.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive', '0001_initial'),
        ('profiles', '0009_alter_profile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsession',
            name='claimed_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_identity_claims', to='profiles.profile', verbose_name='cadastro reivindicado'),
        ),
        migrations.AddField(
            model_name='portalsession',
            name='identity_step',
            field=models.CharField(blank=True, choices=[('awaiting_cpf', 'Aguardando CPF'), ('awaiting_confirm', 'Confirmando identidade'), ('awaiting_selfie', 'Aguardando selfie'), ('done', 'Concluída')], default='', max_length=20, verbose_name='etapa de identidade'),
        ),
        migrations.AlterField(
            model_name='portalevent',
            name='event',
            field=models.CharField(choices=[('connected', 'Conectado (MAC conhecido)'), ('redirect_portal', 'Redirect pro portal'), ('otp_sent', 'OTP enviado'), ('otp_verified', 'OTP confirmado'), ('otp_failed', 'OTP incorreto/expirado'), ('whatsapp_invalid', 'Número sem WhatsApp'), ('visitor_created', 'Visitante criado'), ('cpf_enriched', 'CPF enriquecido'), ('cpf_conflict', 'CPF duplicado'), ('identity_confirm_asked', 'Confirmação de identidade pedida'), ('identity_confirmed', 'Identidade confirmada'), ('identity_denied', 'Identidade negada'), ('selfie_submitted', 'Selfie enviada'), ('selfie_skipped', 'Selfie pulada'), ('profile_merged', 'Cadastros fundidos'), ('role_assigned', 'Papel concedido'), ('lgpd_accepted', 'Termos LGPD aceitos'), ('welcome_scheduled', 'Boas-vindas agendadas'), ('grant_push_failed', 'Push de liberação falhou'), ('internet_released', 'Internet liberada'), ('disconnected', 'Desconectado')], max_length=30, verbose_name='evento'),
        ),
        migrations.CreateModel(
            name='CaptiveConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('kind', models.CharField(choices=[('terms', 'Termos de uso e privacidade'), ('biometric', 'Dado biométrico (selfie)')], default='terms', max_length=20, verbose_name='tipo')),
                ('terms_version', models.CharField(blank=True, default='', max_length=20, verbose_name='versão dos termos')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='aceito em')),
                ('mac', models.CharField(blank=True, db_index=True, default='', max_length=17, verbose_name='mac')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='telefone')),
                ('user_agent', models.CharField(blank=True, default='', max_length=300, verbose_name='user agent')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='evidência')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captive_consents', to='profiles.profile', verbose_name='perfil')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='captive.portalsession', verbose_name='sessão')),
            ],
            options={
                'verbose_name': 'consentimento LGPD',
                'verbose_name_plural': 'consentimentos LGPD',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalSelfie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('image', models.ImageField(blank=True, null=True, storage=apps.captive.models.selfie_storage, upload_to=apps.captive.models.selfie_upload_path, verbose_name='foto')),
                ('status', models.CharField(choices=[('auto_approved', 'Aceita automaticamente'), ('approved', 'Aprovada na conferência'), ('rejected', 'Rejeitada na conferência'), ('skipped', 'Pulada')], default='auto_approved', max_length=20, verbose_name='situação')),
                ('captured_via', models.CharField(blank=True, default='', max_length=16, verbose_name='origem')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='conferida em')),
                ('claimed_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_selfie_claims', to='profiles.profile', verbose_name='cadastro reivindicado')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfies_conferidas', to=settings.AUTH_USER_MODEL, verbose_name='conferida por')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_selfies', to='profiles.profile', verbose_name='quem enviou')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfies', to='captive.portalsession', verbose_name='sessão')),
            ],
            options={
                'verbose_name': 'selfie do portal',
                'verbose_name_plural': 'selfies do portal',
                'ordering': ['-created_at'],
            },
        ),
    ]
