# Generated by Django 6.0.3 on 2026-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive', '0002_portalsession_claimed_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captiveconsent',
            name='terms_text',
            field=models.TextField(blank=True, default='', verbose_name='texto aceito'),
        ),
    ]
