# Generated by Django 6.0.2 on 2026-03-24 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroqVisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_path', models.CharField(help_text='Caminho local da imagem analisada', max_length=500)),
                ('prompt_text', models.TextField(help_text='Texto do prompt enviado à API')),
                ('response_text', models.TextField(blank=True, help_text='Resposta em texto retornada pela API', null=True)),
                ('request_data', models.JSONField(blank=True, help_text='Dados enviados na requisição', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Resposta completa da API em JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log Visão Groq',
                'verbose_name_plural': 'Logs Visão Groq',
                'ordering': ['-created_at'],
            },
        ),
    ]
