# Generated by Django 5.1.15 on 2026-08-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_notification_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('ok', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('heal_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'status de serviço',
                'verbose_name_plural': 'status de serviços',
            },
        ),
    ]
