# Generated by Django 5.2.14 on 2026-06-01 03:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("checkout_url", models.TextField(blank=True, null=True)),
                (
                    "slug",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PAID", "Paid")],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("amount_cents", models.IntegerField()),
                ("paid_amount_cents", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("installments", models.IntegerField(blank=True, null=True)),
                (
                    "capture_method",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "transaction_nsu",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("receipt_url", models.TextField(blank=True, null=True)),
                ("request_payload", models.JSONField(default=dict)),
                ("response_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "order_nsu",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("forwarded_ok", models.BooleanField(default=False)),
                ("forwarded_at", models.DateTimeField(blank=True, null=True)),
                ("source_ip", models.CharField(blank=True, max_length=64, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
