# Generated by Django 5.1.15 on 2026-07-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(max_length=200)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(max_length=200)),
                ('smtp_password', models.CharField(max_length=500)),
                ('from_name', models.CharField(max_length=100)),
                ('from_email', models.EmailField(max_length=254)),
                ('timeout', models.IntegerField(default=10)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_identities', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='TtsVoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_male', models.CharField(help_text='Voice ID que o HOMEM recebe (voz feminina — regra cruzada).', max_length=100)),
                ('voice_female', models.CharField(help_text='Voice ID que a MULHER recebe (voz masculina — regra cruzada).', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_voices', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100)),
                ('driver', models.CharField(choices=[('evolution-v2', 'Evolution v2'), ('evolution-go', 'Evolution Go')], default='evolution-v2', max_length=20)),
                ('slug', models.SlugField()),
                ('is_default', models.BooleanField(default=False)),
                ('connection_status', models.CharField(default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_numbers', to='accounts.account')),
            ],
            options={
                'unique_together': {('account', 'slug')},
            },
        ),
    ]
