# Generated by Django 5.1.15 on 2026-07-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnumber',
            name='fallback_driver',
            field=models.CharField(blank=True, choices=[('evolution-v2', 'Evolution v2'), ('evolution-go', 'Evolution Go')], default='', help_text='Para onde cair quando a sessão do driver preferido estiver fora. Vazio = sem fallback.', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='go_token',
            field=models.CharField(blank=True, default='', help_text='Token da instância na Evolution GO (Fernet). Vazio = usa a key global.', max_length=500),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text="E.164 sem '+', ex.: 554220181533. Dono da instância nos dois provedores.", max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappnumber',
            name='status_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
