# Generated by Django 5.1.15 on 2026-08-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_ai_adapt'),
        ('channels', '0004_mailtemplate_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=500)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('payload_preview', models.CharField(blank=True, default='', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='accounts.account')),
            ],
            options={
                'verbose_name': 'entrega de webhook',
                'verbose_name_plural': 'entregas de webhook',
            },
        ),
    ]
