# Generated by Django 5.1.15 on 2026-08-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_ai_adapt'),
        ('channels', '0005_webhook_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressed_emails', to='accounts.account')),
            ],
            options={
                'verbose_name': 'e-mail suprimido (bounce)',
                'verbose_name_plural': 'e-mails suprimidos (bounce)',
                'unique_together': {('account', 'email')},
            },
        ),
    ]
