# Generated by Django 5.2.14 on 2026-06-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("deepseek", "DeepSeek")], max_length=20),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("json", "json"),
                            ("chat", "chat"),
                            ("summarize", "summarize"),
                            ("extract", "extract"),
                            ("grade", "grade"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(max_length=60)),
                ("caller", models.CharField(db_index=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "success"), ("error", "error")],
                        max_length=10,
                    ),
                ),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("cache_hit_tokens", models.IntegerField(default=0)),
                ("cache_miss_tokens", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("latency_ms", models.IntegerField()),
                (
                    "finish_reason",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="ai_aicall_created_c0cafa_idx"
                    )
                ],
            },
        ),
    ]
