# Generated by Django 5.2.14 on 2026-06-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aicall",
            name="provider",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
