# Generated by Django 5.2.14 on 2026-06-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_alter_aicall_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aicall",
            name="operation",
            field=models.CharField(
                choices=[
                    ("text", "text"),
                    ("json", "json"),
                    ("chat", "chat"),
                    ("summarize", "summarize"),
                    ("extract", "extract"),
                    ("grade", "grade"),
                    ("vision", "vision"),
                    ("image", "image"),
                    ("tts", "tts"),
                    ("ocr", "ocr"),
                ],
                max_length=20,
            ),
        ),
    ]
