# Generated by Django 6.0.3 on 2026-07-25 21:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0009_alter_profile_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="CpfRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=11, unique=True, verbose_name="cpf"),
                ),
                (
                    "enriched",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="enriquecimento"
                    ),
                ),
                (
                    "enriched_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="enriquecido em"
                    ),
                ),
                (
                    "pending_enrichment",
                    models.BooleanField(
                        default=False, verbose_name="enriquecimento pendente"
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpf_record",
                        to="profiles.profile",
                        verbose_name="perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de CPF",
                "verbose_name_plural": "registros de CPF",
            },
        ),
        migrations.CreateModel(
            name="MacBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "mac",
                    models.CharField(max_length=17, unique=True, verbose_name="mac"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="visto por último em"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mac_bindings",
                        to="profiles.profile",
                        verbose_name="perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo de MAC",
                "verbose_name_plural": "vínculos de MAC",
            },
        ),
        migrations.CreateModel(
            name="PortalSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "mac",
                    models.CharField(db_index=True, max_length=17, verbose_name="mac"),
                ),
                (
                    "ssid",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="ssid"
                    ),
                ),
                (
                    "ap_mac",
                    models.CharField(
                        blank=True, default="", max_length=17, verbose_name="mac do ap"
                    ),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="ip do cliente"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "No portal"),
                            ("awaiting_otp", "Aguardando OTP"),
                            ("authorized", "Liberado"),
                            ("closed", "Encerrada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "pending_profile_uuid",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=36,
                        verbose_name="profile uuid pendente",
                    ),
                ),
                (
                    "pending_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="telefone pendente",
                    ),
                ),
                (
                    "pending_first_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="primeiro nome pendente",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[("member", "Membro"), ("visitor", "Visitante")],
                        default="",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "otp_attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="tentativas de otp"
                    ),
                ),
                (
                    "otp_locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="otp bloqueado até"
                    ),
                ),
                (
                    "cpf_completed",
                    models.BooleanField(
                        default=False, verbose_name="etapa cpf concluída"
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="conectado em"
                    ),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="desconectado em"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_sessions",
                        to="profiles.profile",
                        verbose_name="perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "sessão do portal",
                "verbose_name_plural": "sessões do portal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("connected", "Conectado (MAC conhecido)"),
                            ("redirect_portal", "Redirect pro portal"),
                            ("otp_sent", "OTP enviado"),
                            ("otp_verified", "OTP confirmado"),
                            ("otp_failed", "OTP incorreto/expirado"),
                            ("whatsapp_invalid", "Número sem WhatsApp"),
                            ("visitor_created", "Visitante criado"),
                            ("cpf_enriched", "CPF enriquecido"),
                            ("cpf_conflict", "CPF duplicado"),
                            ("welcome_scheduled", "Boas-vindas agendadas"),
                            ("grant_push_failed", "Push de liberação falhou"),
                            ("internet_released", "Internet liberada"),
                            ("disconnected", "Desconectado"),
                        ],
                        max_length=30,
                        verbose_name="evento",
                    ),
                ),
                (
                    "mac",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=17,
                        verbose_name="mac",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="dados"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="captive.portalsession",
                        verbose_name="sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento do portal",
                "verbose_name_plural": "eventos do portal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "mac",
                    models.CharField(db_index=True, max_length=17, verbose_name="mac"),
                ),
                (
                    "credential",
                    models.TextField(unique=True, verbose_name="credencial"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("delivered", "Entregue (push)"),
                            ("acked", "Aplicada no controlador"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=43200, verbose_name="duração (s)"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expira em")),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="entregue em"
                    ),
                ),
                (
                    "acked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="aplicada em"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="tentativas de push"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, default="", verbose_name="último erro"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="captive.portalsession",
                        verbose_name="sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "liberação de acesso",
                "verbose_name_plural": "liberações de acesso",
                "ordering": ["-created_at"],
            },
        ),
    ]
