# Generated by Django 5.2.14 on 2026-05-31 18:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("asaas_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("cpf_cnpj", models.CharField(db_index=True, max_length=14)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OutboundJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField()),
                ("payload", models.JSONField(default=dict)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=6)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PixKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("key_type", models.CharField(max_length=10)),
                ("holder_document", models.CharField(db_index=True, max_length=14)),
                ("holder_name", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                ("raw_dict", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="UrlVerifyNonce",
            fields=[
                (
                    "nonce",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("target_url", models.TextField()),
                ("purpose", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("event", models.CharField(db_index=True, max_length=255)),
                ("payload", models.JSONField(default=dict)),
                ("forwarded_ok", models.BooleanField(default=False)),
                ("forwarded_at", models.DateTimeField(blank=True, null=True)),
                ("source_ip", models.CharField(blank=True, max_length=64, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(max_length=255, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pixkey", "Pixkey"),
                            ("qrcode", "Qrcode"),
                            ("charge", "Charge"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("qrcode_payload", models.TextField(blank=True, null=True)),
                ("pix_qr_image", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(db_index=True, max_length=20)),
                (
                    "asaas_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="asaas.customer",
                    ),
                ),
                (
                    "pix_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="asaas.pixkey",
                    ),
                ),
            ],
        ),
    ]
