# Generated by Django 5.2.14 on 2026-06-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asaas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("pixkey", "Pixkey"),
                    ("qrcode", "Qrcode"),
                    ("charge", "Charge"),
                    ("boleto", "Boleto"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
