# Generated by Django 5.2.16 on 2026-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas', '0004_payment_bank_slip_url_payment_billing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('pixkey', 'Pixkey'), ('qrcode', 'Qrcode'), ('charge', 'Charge'), ('boleto', 'Boleto'), ('static_pix_qr', 'Static Pix Qr')], db_index=True, max_length=14),
        ),
    ]
