# Generated by Django 5.1.15 on 2026-08-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_inboundevent_forwarded_inboundevent_from_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='driver_reason',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
    ]
