# Generated by Django 5.1.15 on 2026-08-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_notification_driver_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
