# Generated by Django 5.1.15 on 2026-08-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_webhookevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tts_audio_path',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tts_error',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tts_status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='want_tts',
        ),
        migrations.RemoveField(
            model_name='template',
            name='is_tts',
        ),
    ]
