# Generated by Django 6.0.3 on 2026-07-28 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0009_alter_profile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(choices=[('visitante', 'Visitante'), ('congregado', 'Congregado'), ('membro', 'Membro')], max_length=16, verbose_name='papel')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='concedido em')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('source', models.CharField(blank=True, max_length=32, verbose_name='origem')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papeis_concedidos', to=settings.AUTH_USER_MODEL, verbose_name='concedido por')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='profiles.profile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'papel do perfil',
                'verbose_name_plural': 'papéis dos perfis',
                'ordering': ('-granted_at',),
                'indexes': [models.Index(fields=['profile', 'is_active'], name='roles_profi_profile_184d12_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('profile',), name='uniq_active_role_per_profile')],
            },
        ),
    ]
