# Generated by Django 5.2.14 on 2026-05-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UnroutedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=64)),
                ("event", models.CharField(db_index=True, max_length=255)),
                ("reason", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved", models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
