# Generated by Django 5.2.14 on 2026-06-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(db_index=True, max_length=128)),
                ("passed", models.BooleanField()),
                ("mode", models.CharField(blank=True, max_length=32)),
                ("detail", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope", "name", "-checked_at"],
                        name="core_valida_scope_fc2e56_idx",
                    )
                ],
            },
        ),
    ]
