# Generated by Django 6.0.3 on 2026-04-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_alter_address_options_alter_addressproof_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('content', models.TextField(help_text='Texto em Markdown ou URL de mídia', verbose_name='conteúdo')),
                ('template_name', models.CharField(blank=True, help_text='Nome do template HTML para e-mail (sem extensão)', max_length=100, verbose_name='nome do template')),
                ('is_media', models.BooleanField(default=False, help_text='True se content for URL de imagem/vídeo/áudio', verbose_name='é mídia')),
                ('media_type', models.CharField(blank=True, choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('document', 'Documento')], default='text', max_length=20, verbose_name='tipo de mídia')),
                ('use_tts', models.BooleanField(default=False, help_text='Gera áudio com ElevenLabs para WhatsApp', verbose_name='usar TTS')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='status')),
                ('channel_sent', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('both', 'Ambos')], max_length=20, verbose_name='canal enviado')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='agendado para')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processado em')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('event_key', models.CharField(blank=True, default='', max_length=120, verbose_name='chave do evento')),
                ('last_error_message', models.TextField(blank=True, default='', verbose_name='último erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='profiles.profile', verbose_name='destinatário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('both', 'Ambos')], max_length=20, verbose_name='canal')),
                ('success', models.BooleanField(default=False, verbose_name='sucesso')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='resposta da API')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120, verbose_name='id da mensagem no provedor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification', verbose_name='notificação')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
