# Generated by Django 6.0.3 on 2026-04-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_media_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(help_text='Título e texto sempre em Markdown.', verbose_name='conteúdo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_media',
            field=models.BooleanField(default=False, help_text='Indica se há payload de mídia associado à notificação.', verbose_name='tem mídia'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='media_payload',
            field=models.TextField(blank=True, default='', help_text='Base64 puro, data URL ou URL pública da mídia.', verbose_name='payload da mídia'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='media_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('document', 'Documento')], default='text', max_length=20, verbose_name='tipo de mídia'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='template_name',
            field=models.CharField(blank=True, help_text='Template HTML do e-mail. Padrão: email_notification.html', max_length=100, verbose_name='nome do template'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='use_tts',
            field=models.BooleanField(default=False, help_text='Quando ativo, o WhatsApp envia áudio gerado pelo ElevenLabs.', verbose_name='usar TTS'),
        ),
    ]
