# Generated by Django 5.1.15 on 2026-08-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_appwebhook_mailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
