# Generated by Django 5.1.15 on 2026-08-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_whatsappnumber_driver_go_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappnumber',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text="E.164 sem '+', ex.: 554220181533. Dono da instância.", max_length=20),
        ),
        migrations.DeleteModel(
            name='TtsVoices',
        ),
    ]
