# Generated by Django 5.1.15 on 2026-07-17 21:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('instance_name', models.CharField(max_length=100)),
                ('wa_message_id', models.CharField(max_length=100, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_events', to='accounts.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event', models.SlugField(max_length=80)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body_md', models.TextField(help_text='Markdown. Placeholders {nome}, {nome-completo}, {valor}...')),
                ('is_tts', models.BooleanField(default=False)),
                ('storytelling', models.BooleanField(default=False)),
                ('story_prompt', models.TextField(blank=True, null=True)),
                ('channels', models.CharField(default='whatsapp,email', max_length=40)),
                ('media_url', models.CharField(blank=True, max_length=500, null=True)),
                ('media_type', models.CharField(blank=True, max_length=20, null=True)),
                ('mail_template', models.CharField(default='default', max_length=50)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='accounts.account')),
            ],
            options={
                'verbose_name': 'template de notificação',
                'verbose_name_plural': 'templates de notificação',
                'unique_together': {('account', 'event')},
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fires_on', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trigger', to='notify.template')),
            ],
            options={
                'verbose_name': 'gatilho de notificação',
                'verbose_name_plural': 'gatilhos de notificação',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('caller', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_template', models.CharField(default='default', max_length=50)),
                ('media_url', models.CharField(blank=True, max_length=500, null=True)),
                ('media_type', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('want_whatsapp', models.BooleanField(default=True)),
                ('want_email', models.BooleanField(default=False)),
                ('want_tts', models.BooleanField(default=False)),
                ('whatsapp_status', models.CharField(choices=[('pending', 'pendente'), ('sending', 'enviando'), ('sent', 'enviado'), ('failed', 'falhou'), ('skipped', 'ignorado')], default='pending', max_length=10)),
                ('email_status', models.CharField(choices=[('pending', 'pendente'), ('sending', 'enviando'), ('sent', 'enviado'), ('failed', 'falhou'), ('skipped', 'ignorado')], default='pending', max_length=10)),
                ('tts_status', models.CharField(choices=[('pending', 'pendente'), ('sending', 'enviando'), ('sent', 'enviado'), ('failed', 'falhou'), ('skipped', 'ignorado')], default='pending', max_length=10)),
                ('whatsapp_error', models.TextField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True, null=True)),
                ('tts_error', models.TextField(blank=True, null=True)),
                ('tts_audio_path', models.CharField(blank=True, max_length=500, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.account')),
                ('whatsapp_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='channels.whatsappnumber')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', None), _negated=True), fields=('account', 'idempotency_key'), name='uniq_account_idempotency_key')],
            },
        ),
    ]
