# Generated by Django 5.1.15 on 2026-07-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundevent',
            name='forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboundevent',
            name='from_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='inboundevent',
            name='preview',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_status',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='notification',
            name='driver_used',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_status',
            field=models.CharField(choices=[('pending', 'pendente'), ('sending', 'enviando'), ('sent', 'enviado'), ('failed', 'falhou'), ('skipped', 'ignorado')], default='skipped', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='want_sms',
            field=models.BooleanField(default=False),
        ),
    ]
