# Generated by Django 5.1.15 on 2026-08-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_color_primary_account_logo'),
        ('notify', '0005_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, max_length=20)),
                ('category', models.SlugField(max_length=80)),
                ('summary', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'aberta'), ('acknowledged', 'em análise'), ('resolved', 'resolvida')], default='open', max_length=12)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='accounts.account')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='notify.notification')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status', '-updated_at'], name='notify_comp_status_e7b8c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemplateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.SlugField(max_length=80)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_md', models.TextField(help_text='Markdown proposto. Placeholders {nome}, {nome-completo}…')),
                ('is_tts', models.BooleanField(default=False)),
                ('channels', models.CharField(default='whatsapp,email', max_length=40)),
                ('media_url', models.CharField(blank=True, max_length=500)),
                ('media_type', models.CharField(blank=True, max_length=20)),
                ('mail_template', models.CharField(blank=True, default='default', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'pendente'), ('approved', 'aprovada'), ('rejected', 'rejeitada')], default='pending', max_length=10)),
                ('requested_by', models.CharField(max_length=100)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_requests', to='accounts.account')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['account', 'status'], name='notify_temp_account_f273a3_idx')],
            },
        ),
    ]
