# Generated by Django 5.2.14 on 2026-06-05 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceBiometric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("document", "documento"), ("selfie", "selfie")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("image_path", models.CharField(max_length=500)),
                ("embedding", models.JSONField(default=list)),
                ("det_score", models.FloatField(blank=True, null=True)),
                ("provider", models.CharField(default="insightface", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_biometrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaceVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("caller", models.CharField(db_index=True, max_length=64)),
                ("score", models.FloatField(blank=True, null=True)),
                ("threshold", models.FloatField()),
                ("approved", models.BooleanField(default=False)),
                ("status", models.CharField(db_index=True, max_length=16)),
                ("provider", models.CharField(default="insightface", max_length=32)),
                ("liveness", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "probe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="biometric.facebiometric",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="biometric.facebiometric",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="facebiometric",
            index=models.Index(
                fields=["user", "source", "-created_at"],
                name="biometric_f_user_id_aabcd6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="faceverification",
            index=models.Index(
                fields=["user", "-created_at"], name="biometric_f_user_id_632b89_idx"
            ),
        ),
    ]
